-- Rollback for the unapplied proposal; not executed.
alter policy "audit_read" on public."audit_logs" using ((my_role() = ANY (ARRAY['admin'::text, 'exec'::text, 'finance'::text])));
alter policy "boqi_read" on public."boq_items" using ((my_role() = ANY (ARRAY['admin'::text, 'exec'::text, 'finance'::text, 'sales'::text, 'stock'::text, 'hr'::text])));
alter policy "boq_read" on public."boqs" using ((my_role() = ANY (ARRAY['admin'::text, 'exec'::text, 'finance'::text, 'sales'::text, 'stock'::text, 'hr'::text])));
alter policy "cn_read" on public."chat_notes" using ((chat_is_member(room_id) OR (my_role() = ANY (ARRAY['admin'::text, 'exec'::text, 'finance'::text, 'sales'::text]))));
alter policy "cr_read" on public."chat_rooms" using (((kind = 'company'::text) OR chat_is_member(id) OR ((kind = ANY (ARRAY['group'::text, 'project'::text])) AND (my_role() = ANY (ARRAY['admin'::text, 'exec'::text, 'finance'::text, 'sales'::text])))));
alter policy "email_messages_read" on public."email_messages" using ((my_role() = ANY (ARRAY['admin'::text, 'exec'::text, 'finance'::text, 'hr'::text, 'sales'::text, 'field_sales'::text, 'graphic'::text])));
alter policy "email_threads_read" on public."email_threads" using ((my_role() = ANY (ARRAY['admin'::text, 'exec'::text, 'finance'::text, 'hr'::text, 'sales'::text, 'field_sales'::text, 'graphic'::text])));
alter policy "er_read" on public."expense_requests" using (((requester = auth.uid()) OR (my_role() = ANY (ARRAY['admin'::text, 'exec'::text, 'finance'::text, 'hr'::text]))));
alter policy "fb_contacts_read" on public."fb_contacts" using ((my_role() = ANY (ARRAY['admin'::text, 'sales'::text, 'exec'::text, 'finance'::text, 'lead_tech'::text, 'hr'::text])));
alter policy "fb_messages_read" on public."fb_messages" using ((my_role() = ANY (ARRAY['admin'::text, 'sales'::text, 'exec'::text, 'finance'::text, 'lead_tech'::text, 'hr'::text])));
alter policy "handbook_ack_read" on public."handbook_ack" using (((user_id = auth.uid()) OR (my_role() = ANY (ARRAY['admin'::text, 'exec'::text, 'hr'::text]))));
alter policy "hr_loans_sel" on public."hr_loans" using (((user_id = auth.uid()) OR (my_role() = ANY (ARRAY['admin'::text, 'exec'::text, 'hr'::text, 'finance'::text]))));
alter policy "hr_ot_sel" on public."hr_ot" using (((user_id = auth.uid()) OR (my_role() = ANY (ARRAY['admin'::text, 'exec'::text, 'hr'::text]))));
alter policy "hr_pay_read" on public."hr_pay" using (((user_id = auth.uid()) OR (my_role() = ANY (ARRAY['admin'::text, 'exec'::text, 'hr'::text, 'finance'::text]))));
alter policy "hr_profiles_read" on public."hr_profiles" using (((user_id = auth.uid()) OR (my_role() = ANY (ARRAY['admin'::text, 'exec'::text, 'hr'::text]))));
alter policy "job_handovers_read" on public."job_handovers" using (((created_by = auth.uid()) OR (my_role() = ANY (ARRAY['admin'::text, 'exec'::text, 'sales'::text, 'finance'::text, 'lead_tech'::text, 'hr'::text, 'stock'::text]))));
alter policy "lcc_read" on public."line_contact_customers" using ((my_role() = ANY (ARRAY['admin'::text, 'sales'::text, 'exec'::text, 'finance'::text, 'lead_tech'::text, 'hr'::text])));
alter policy "lc_read" on public."line_contacts" using ((my_role() = ANY (ARRAY['admin'::text, 'sales'::text, 'exec'::text, 'finance'::text, 'lead_tech'::text, 'hr'::text])));
alter policy "lm_read" on public."line_messages" using ((my_role() = ANY (ARRAY['admin'::text, 'sales'::text, 'exec'::text, 'finance'::text, 'lead_tech'::text, 'hr'::text])));
alter policy "poi_sel" on public."po_items" using ((my_role() = ANY (ARRAY['admin'::text, 'exec'::text, 'finance'::text, 'stock'::text, 'sales'::text, 'hr'::text])));
alter policy "promo_coup_read" on public."promo_coupons" using ((my_role() = ANY (ARRAY['admin'::text, 'exec'::text, 'finance'::text, 'sales'::text, 'field_sales'::text, 'stock'::text, 'hr'::text])));
alter policy "po_sel" on public."purchase_orders" using ((my_role() = ANY (ARRAY['admin'::text, 'exec'::text, 'finance'::text, 'stock'::text, 'sales'::text, 'hr'::text])));
alter policy "qr_read" on public."quick_replies" using ((my_role() = ANY (ARRAY['admin'::text, 'sales'::text, 'exec'::text, 'finance'::text, 'lead_tech'::text, 'hr'::text])));
alter policy "qti_read" on public."quotation_items" using ((my_role() = ANY (ARRAY['admin'::text, 'exec'::text, 'finance'::text, 'sales'::text, 'stock'::text, 'hr'::text])));
alter policy "qt_read" on public."quotations" using ((my_role() = ANY (ARRAY['admin'::text, 'exec'::text, 'finance'::text, 'sales'::text, 'stock'::text, 'hr'::text])));
alter policy "sci_read" on public."stock_count_items" using ((my_role() = ANY (ARRAY['admin'::text, 'exec'::text, 'finance'::text, 'stock'::text])));
alter policy "sc_read" on public."stock_counts" using ((my_role() = ANY (ARRAY['admin'::text, 'exec'::text, 'finance'::text, 'stock'::text])));
alter policy "sub_payouts_read" on public."sub_payouts" using ((my_role() = ANY (ARRAY['admin'::text, 'exec'::text, 'finance'::text, 'sales'::text, 'hr'::text])));
alter policy "txn_read" on public."transactions" using (((my_role() = ANY (ARRAY['admin'::text, 'exec'::text, 'finance'::text, 'stock'::text, 'sales'::text, 'lead_tech'::text, 'hr'::text])) OR (team = my_team())));
alter policy "wad_read" on public."web_ads" using (((active = true) OR (my_role() = ANY (ARRAY['admin'::text, 'sales'::text, 'exec'::text, 'finance'::text, 'graphic'::text]))));
alter policy "wcnt_read" on public."web_articles" using (((active = true) OR (my_role() = ANY (ARRAY['admin'::text, 'sales'::text, 'exec'::text, 'finance'::text, 'graphic'::text]))));
alter policy "wb_read" on public."web_banners" using (((active = true) OR (my_role() = ANY (ARRAY['admin'::text, 'sales'::text, 'exec'::text, 'finance'::text, 'graphic'::text]))));
alter policy "wc_read" on public."web_clients" using (((active = true) OR (my_role() = ANY (ARRAY['admin'::text, 'sales'::text, 'exec'::text, 'finance'::text, 'graphic'::text]))));
alter policy "web_orders_read" on public."web_orders" using ((my_role() = ANY (ARRAY['admin'::text, 'sales'::text, 'exec'::text, 'finance'::text, 'hr'::text, 'graphic'::text])));
alter policy "wcnt_read" on public."web_portfolio" using (((active = true) OR (my_role() = ANY (ARRAY['admin'::text, 'sales'::text, 'exec'::text, 'finance'::text, 'graphic'::text]))));
alter policy "wcnt_read" on public."web_press" using (((active = true) OR (my_role() = ANY (ARRAY['admin'::text, 'sales'::text, 'exec'::text, 'finance'::text, 'graphic'::text]))));
alter policy "wrev_read" on public."web_reviews" using (((active = true) OR (my_role() = ANY (ARRAY['admin'::text, 'sales'::text, 'exec'::text, 'graphic'::text, 'finance'::text]))));
alter policy "wsvc_read" on public."web_services" using (((active = true) OR (my_role() = ANY (ARRAY['admin'::text, 'sales'::text, 'exec'::text, 'graphic'::text, 'finance'::text]))));
