// เงื่อนไขรับประกันแอร์ "รายซีรีส์" — ค้นจากเว็บ/โบรชัวร์ผู้ผลิต แล้วผ่านการตรวจสอบแย้งอีกชั้น (18 ก.ค. 2026)
// แทนข้อความรวมระดับยี่ห้อจาก migration 140 ที่กว้างเกินไป (เช่น Carrier "7–10 ปี ตามซีรีส์")
//
// conf: high = หน้า/PDF ทางการระบุของซีรีส์นั้นตรง ๆ · medium = ทางการแต่เป็นเงื่อนไขรวมกลุ่มสินค้า · low = ยืนยันจากแหล่งรอง ควรเช็กกับตัวแทนก่อนใช้ในสัญญาใหญ่
// ข้อความนี้พิมพ์ลงใบเสนอราคาได้ทันที (ผ่านช่อง 'การรับประกัน' ในเงื่อนไขท้ายเอกสาร)

export const AC_WARRANTY = [
  { brand: "Amena", series: "AMENA WL", warranty: "คอมเพรสเซอร์ 5 ปี · อะไหล่ 2 ปี", conf: "low" },
  { brand: "Amena", series: "AMENA WR", warranty: "คอมเพรสเซอร์ 10 ปี · อะไหล่ 2 ปี", conf: "low" },
  { brand: "Amena", series: "Type DCC", warranty: "คอมเพรสเซอร์ 5 ปี · อะไหล่ 2 ปี", conf: "low" },
  { brand: "AUX", series: "AUX MF", warranty: "คอมเพรสเซอร์ 10 ปี · อะไหล่ 5 ปี (ยังไม่ยืนยัน — ห้ามพิมพ์จนกว่าจะได้เอกสารจากผู้แทนจำหน่าย)", conf: "low" },
  { brand: "Carrier", series: "40QBU", warranty: "คอมเพรสเซอร์ 1 ปี · อะไหล่ 1 ปี", conf: "high" },
  { brand: "Carrier", series: "Apollo lll", warranty: "คอมเพรสเซอร์ 5 ปี · อะไหล่ 1 ปี", conf: "medium" },
  { brand: "Carrier", series: "Cassette TGEV", warranty: "คอมเพรสเซอร์ 7 ปี · อะไหล่ 2 ปี", conf: "high" },
  { brand: "Carrier", series: "Cassette TGF", warranty: "คอมเพรสเซอร์ 5 ปี · อะไหล่ 1 ปี", conf: "high" },
  { brand: "Carrier", series: "Cassette TGV", warranty: "คอมเพรสเซอร์ 7 ปี · อะไหล่ 2 ปี", conf: "high" },
  { brand: "Carrier", series: "Cassette VLJ", warranty: "คอมเพรสเซอร์ 5 ปี · อะไหล่ 1 ปี", conf: "high" },
  { brand: "Carrier", series: "Ceiling TGEV", warranty: "คอมเพรสเซอร์ 7 ปี · อะไหล่ 2 ปี", conf: "high" },
  { brand: "Carrier", series: "Ceiling TGF", warranty: "คอมเพรสเซอร์ 5 ปี · อะไหล่ 1 ปี", conf: "high" },
  { brand: "Carrier", series: "Ceiling TGV", warranty: "คอมเพรสเซอร์ 7 ปี · อะไหล่ 2 ปี", conf: "high" },
  { brand: "Carrier", series: "FCU", warranty: "อะไหล่ 1 ปี", conf: "low" },
  { brand: "Carrier", series: "NSAA", warranty: "คอมเพรสเซอร์ 7 ปี · อะไหล่ 3 ปี · ฟรีค่าแรง 1 ปี", conf: "high" },
  { brand: "Carrier", series: "NVAA", warranty: "คอมเพรสเซอร์ 10 ปี · อะไหล่ 5 ปี · ฟรีค่าแรง 1 ปี", conf: "high" },
  { brand: "Carrier", series: "TGF", warranty: "คอมเพรสเซอร์ 5 ปี · อะไหล่ 1 ปี", conf: "low" },
  { brand: "Carrier", series: "TGV", warranty: "คอมเพรสเซอร์ 7 ปี · อะไหล่ 2 ปี", conf: "medium" },
  { brand: "Carrier", series: "TSAA", warranty: "คอมเพรสเซอร์ 7 ปี · อะไหล่ 3 ปี · ฟรีค่าแรง 3 ปี", conf: "medium" },
  { brand: "Carrier", series: "TVAB", warranty: "คอมเพรสเซอร์ 10 ปี · อะไหล่ 5 ปี · ฟรีค่าแรง 3 ปี", conf: "medium" },
  { brand: "Carrier", series: "Way TGF", warranty: "คอมเพรสเซอร์ 5 ปี · อะไหล่ 1 ปี", conf: "medium" },
  { brand: "Carrier", series: "Way TGV", warranty: "คอมเพรสเซอร์ 7 ปี · อะไหล่ 2 ปี", conf: "medium" },
  { brand: "Central", series: "Cassette IVSA", warranty: "คอมเพรสเซอร์ 5 ปี · อะไหล่ 2 ปี", conf: "high" },
  { brand: "Central", series: "Ceiling IVSA", warranty: "คอมเพรสเซอร์ 5 ปี · อะไหล่ 2 ปี", conf: "high" },
  { brand: "Central", series: "Central ES", warranty: "คอมเพรสเซอร์ 1 ปี · อะไหล่ 1 ปี", conf: "high" },
  { brand: "Central", series: "Central IVGE", warranty: "คอมเพรสเซอร์ 10 ปี · อะไหล่ 2 ปี", conf: "high" },
  { brand: "Central", series: "Central IVJS", warranty: "คอมเพรสเซอร์ 10 ปี · อะไหล่ 5 ปี", conf: "high" },
  { brand: "Central", series: "Central IVM", warranty: "คอมเพรสเซอร์ 10 ปี · อะไหล่ 5 ปี", conf: "high" },
  { brand: "Central", series: "Central JSFE", warranty: "คอมเพรสเซอร์ 10 ปี · อะไหล่ 3 ปี", conf: "low" },
  { brand: "Central", series: "Central MFE", warranty: "คอมเพรสเซอร์ 10 ปี · อะไหล่ 3 ปี", conf: "high" },
  { brand: "Central", series: "DA", warranty: "คอมเพรสเซอร์ 1 ปี · อะไหล่ 1 ปี", conf: "low" },
  { brand: "Central", series: "Standing ME", warranty: "คอมเพรสเซอร์ 2 ปี · อะไหล่ 2 ปี", conf: "high" },
  { brand: "Daikin", series: "Cassette FCC", warranty: "คอมเพรสเซอร์ 5 ปี · คอยล์เย็น 3 ปี · อะไหล่อื่น 1 ปี · ฟรีค่าแรง 1 ปี", conf: "high" },
  { brand: "Daikin", series: "Ceiling FHNQ", warranty: "คอมเพรสเซอร์ 5 ปี · คอยล์ร้อน 3 ปี (24/30/36k BTU) หรือ 1 ปี (13/18k BTU) · อะไหล่อื่น 1 ปี · ฟรีค่าแรง 1 ปี", conf: "high" },
  { brand: "Daikin", series: "Daikin FTM", warranty: "คอมเพรสเซอร์ 5 ปี · คอยล์เย็น 3 ปี · อะไหล่อื่น 1 ปี · ฟรีค่าแรง 1 ปี", conf: "high" },
  { brand: "Daikin", series: "FBA", warranty: "คอมเพรสเซอร์ 5 ปี · PCB เครื่องภายนอก 3 ปี · คอยล์เย็น 3 ปี · คอยล์ร้อน 3 ปี · อะไหล่อื่น 1 ปี · ฟรีค่าแรง 1 ปี", conf: "low" },
  { brand: "Daikin", series: "FBFC", warranty: "คอมเพรสเซอร์ 5 ปี · PCB เครื่องภายนอก 3 ปี · คอยล์เย็น 3 ปี · คอยล์ร้อน 3 ปี · อะไหล่อื่น 1 ปี · ฟรีค่าแรง 1 ปี", conf: "low" },
  { brand: "Daikin", series: "FCTF", warranty: "คอมเพรสเซอร์ 5 ปี · PCB เครื่องภายนอก 3 ปี · คอยล์เย็น 3 ปี · คอยล์ร้อน 3 ปี · อะไหล่อื่น 1 ปี · ฟรีค่าแรง 1 ปี", conf: "low" },
  { brand: "Daikin", series: "FDBF", warranty: "คอมเพรสเซอร์ 5 ปี · PCB เครื่องภายนอก 3 ปี · คอยล์เย็น 3 ปี · คอยล์ร้อน 3 ปี · อะไหล่อื่น 1 ปี · ฟรีค่าแรง 1 ปี", conf: "low" },
  { brand: "Daikin", series: "STAR FAVF", warranty: "คอมเพรสเซอร์ 5 ปี · PCB เครื่องภายนอก 3 ปี · คอยล์เย็น 3 ปี · คอยล์ร้อน 3 ปี (30,000 BTU) หรือ 1 ปี (36,000 BTU) · อะไหล่อื่น 1 ปี · ฟรีค่าแรง 1 ปี", conf: "high" },
  { brand: "Daikin", series: "STAR KB", warranty: "คอมเพรสเซอร์ 5 ปี · แผงวงจร PCB (ใน/นอก) 5 ปี · คอยล์เย็น 5 ปี · อะไหล่อื่น 1 ปี · ฟรีค่าแรง 1 ปี", conf: "high" },
  { brand: "Daikin", series: "STAR KF", warranty: "คอมเพรสเซอร์ 5 ปี · แผงวงจร PCB (ใน/นอก) 5 ปี · คอยล์เย็น 5 ปี · คอยล์ร้อน 5 ปี · อะไหล่อื่น 1 ปี · ฟรีค่าแรง 1 ปี", conf: "high" },
  { brand: "Daikin", series: "STAR KM", warranty: "คอมเพรสเซอร์ 5 ปี · แผงวงจร PCB (ใน/นอก) 5 ปี · คอยล์เย็น 5 ปี · คอยล์ร้อน 5 ปี · อะไหล่อื่น 1 ปี · ฟรีค่าแรง 1 ปี", conf: "high" },
  { brand: "Daikin", series: "STAR KQ", warranty: "คอมเพรสเซอร์ 5 ปี · แผงวงจร PCB (ใน/นอก) 5 ปี · คอยล์เย็น 5 ปี · อะไหล่อื่น 1 ปี · ฟรีค่าแรง 1 ปี", conf: "high" },
  { brand: "Daikin", series: "STAR KZ", warranty: "คอมเพรสเซอร์ 5 ปี · แผงวงจร PCB (ใน/นอก) 5 ปี · คอยล์เย็น 5 ปี · คอยล์ร้อน 5 ปี · อะไหล่อื่น 1 ปี · ฟรีค่าแรง 1 ปี", conf: "high" },
  { brand: "Eminent", series: "SUPER KOOM", warranty: "คอมเพรสเซอร์ 5 ปี · อะไหล่ 2 ปี", conf: "low" },
  { brand: "Gree", series: "Cap", warranty: "คอมเพรสเซอร์ 10 ปี · อะไหล่ 5 ปี · ฟรีค่าบริการตรวจเช็ค 1 ปี", conf: "low" },
  { brand: "Gree", series: "Gree SAVI", warranty: "คอมเพรสเซอร์ 10 ปี · อะไหล่ 5 ปี · ฟรีค่าบริการตรวจเช็ค 1 ปี", conf: "low" },
  { brand: "Gree", series: "PULAR I1", warranty: "คอมเพรสเซอร์ 10 ปี · อะไหล่ 5 ปี · ฟรีค่าบริการตรวจเช็ค 1 ปี", conf: "low" },
  { brand: "Haier", series: "Ceiling HCFU", warranty: "ตัวเครื่อง/อะไหล่ 5 ปี · คอมเพรสเซอร์ 5 ปี", conf: "high" },
  { brand: "Haier", series: "Cool Plus", warranty: "ตัวเครื่อง/อะไหล่ 5 ปี · คอมเพรสเซอร์ 10 ปี", conf: "low" },
  { brand: "Haier", series: "Flow HCSI", warranty: "ตัวเครื่อง/อะไหล่ 5 ปี · คอมเพรสเซอร์ 10 ปี", conf: "high" },
  { brand: "Haier", series: "Flow HCSU", warranty: "ตัวเครื่อง/อะไหล่ 5 ปี · คอมเพรสเซอร์ 5 ปี", conf: "low" },
  { brand: "Haier", series: "HDI", warranty: "ตัวเครื่อง/อะไหล่ 5 ปี · คอมเพรสเซอร์ 10 ปี", conf: "high" },
  { brand: "Haier", series: "Way HCS1", warranty: "ตัวเครื่อง/อะไหล่ 5 ปี · คอมเพรสเซอร์ 10 ปี", conf: "high" },
  { brand: "Hisense", series: "Cassette Mark5", warranty: "คอมเพรสเซอร์ 12 ปี · อะไหล่ 3 ปี", conf: "low" },
  { brand: "Hisense", series: "Floor", warranty: "คอมเพรสเซอร์ 12 ปี · อะไหล่ 3 ปี", conf: "low" },
  { brand: "Hisense", series: "Hisense KC", warranty: "คอมเพรสเซอร์ 12 ปี · อะไหล่ 5 ปี", conf: "medium" },
  { brand: "Hisense", series: "Hisense KD", warranty: "คอมเพรสเซอร์ 12 ปี · อะไหล่ 5 ปี", conf: "low" },
  // รุ่นนี้ไม่มีชื่อซีรีส์ในระบบ จึงจับคู่ด้วยรหัสสินค้า
  { brand: "Hisense", code: "AS-24TRLB2T", warranty: "คอมเพรสเซอร์ 12 ปี · อะไหล่ 5 ปี", conf: "medium" },
  { brand: "LG", series: "Cassette ZTNQ", warranty: "คอมเพรสเซอร์ 5 ปี · ตัวเครื่อง/อะไหล่ 1 ปี (ไม่รวมค่าแรง ค่าเดินทาง และอะไหล่เพื่อความสวยงาม)", conf: "low" },
  { brand: "LG", series: "Ceiling ZVNQ", warranty: "คอมเพรสเซอร์ 5 ปี · ตัวเครื่อง/อะไหล่ 1 ปี (ไม่รวมค่าแรง ค่าเดินทาง และอะไหล่เพื่อความสวยงาม)", conf: "low" },
  { brand: "LG", series: "VICTORY IKR", warranty: "คอมเพรสเซอร์ 10 ปี · ตัวเครื่อง 1 ปี · อะไหล่ 3 ปี (ไม่รวมค่าแรงและค่าทำระบบน้ำยา) — สำหรับลูกค้าที่ซื้อตั้งแต่ 1 มกราคม 2568", conf: "medium" },
  { brand: "Midea", series: "Cassette LCAC", warranty: "คอมเพรสเซอร์ 10 ปี · อะไหล่ 5 ปี · ฟรีค่าแรง 5 ปี", conf: "low" },
  { brand: "Midea", series: "Ceiling LCAC", warranty: "คอมเพรสเซอร์ 10 ปี · อะไหล่ 5 ปี · ฟรีค่าแรง 5 ปี", conf: "low" },
  { brand: "Midea", series: "Ceiling ME", warranty: "คอมเพรสเซอร์ 7 ปี · อะไหล่ 5 ปี · ฟรีค่าแรง 5 ปี", conf: "low" },
  { brand: "Midea", series: "MFA", warranty: "คอมเพรสเซอร์ 10 ปี · อะไหล่ 5 ปี · ฟรีค่าแรง 5 ปี", conf: "low" },
  { brand: "Midea", series: "MFGA", warranty: "คอมเพรสเซอร์ 7 ปี · อะไหล่ 5 ปี · ฟรีค่าแรง 5 ปี", conf: "low" },
  { brand: "Midea", series: "MFJ", warranty: "คอมเพรสเซอร์ 7 ปี · อะไหล่ 5 ปี · ฟรีค่าแรง 5 ปี", conf: "low" },
  { brand: "Midea", series: "MFTM", warranty: "คอมเพรสเซอร์ 7 ปี · อะไหล่ 5 ปี · ฟรีค่าแรง 5 ปี", conf: "low" },
  { brand: "Midea", series: "Midea Celest", warranty: "คอมเพรสเซอร์ 10 ปี · อะไหล่ 5 ปี · ฟรีค่าแรง 5 ปี", conf: "low" },
  { brand: "Midea", series: "Midea Numen", warranty: "คอมเพรสเซอร์ 10 ปี · อะไหล่ 5 ปี · ฟรีค่าแรง 5 ปี", conf: "low" },
  { brand: "Midea", series: "MSEPB", warranty: "คอมเพรสเซอร์ 10 ปี · อะไหล่ 5 ปี · ฟรีค่าแรง 5 ปี", conf: "low" },
  { brand: "Midea", series: "MSEPC", warranty: "คอมเพรสเซอร์ 10 ปี · อะไหล่ 5 ปี · ฟรีค่าแรง 5 ปี", conf: "low" },
  { brand: "Midea", series: "MTI", warranty: "คอมเพรสเซอร์ 10 ปี · อะไหล่ 5 ปี · ฟรีค่าแรง 5 ปี", conf: "low" },
  { brand: "Midea", series: "MTIU", warranty: "คอมเพรสเซอร์ 10 ปี · อะไหล่ 5 ปี · ฟรีค่าแรง 5 ปี", conf: "low" },
  { brand: "Midea", series: "Torndo Easy", warranty: "คอมเพรสเซอร์ 7 ปี · อะไหล่ 5 ปี · ฟรีค่าแรง 5 ปี", conf: "low" },
  { brand: "Mitsubishi Electric", series: "AW", warranty: "คอมเพรสเซอร์ 5 ปี · แผงคอยล์ร้อน-เย็น 3 ปี · อะไหล่ภายในตัวเครื่อง 1 ปี", conf: "high" },
  { brand: "Mitsubishi Electric", series: "Cassette PL", warranty: "คอมเพรสเซอร์ 5 ปี · แผงคอยล์ร้อน-เย็น 3 ปี · อะไหล่ภายในตัวเครื่อง 1 ปี", conf: "high" },
  { brand: "Mitsubishi Electric", series: "GY", warranty: "คอมเพรสเซอร์ 5 ปี · แผงคอยล์ร้อน-เย็น 3 ปี · อะไหล่ภายในตัวเครื่อง 1 ปี", conf: "high" },
  { brand: "Mitsubishi Electric", series: "GZ", warranty: "คอมเพรสเซอร์ 5 ปี · แผงคอยล์ร้อน-เย็น 3 ปี · อะไหล่ภายในตัวเครื่อง 1 ปี", conf: "high" },
  { brand: "Mitsubishi Electric", series: "JY", warranty: "คอมเพรสเซอร์ 5 ปี · แผงคอยล์ร้อน-เย็น 3 ปี · อะไหล่ภายในตัวเครื่อง 1 ปี", conf: "high" },
  { brand: "Mitsubishi Electric", series: "JZ", warranty: "คอมเพรสเซอร์ 5 ปี · แผงคอยล์ร้อน-เย็น 3 ปี · อะไหล่ภายในตัวเครื่อง 1 ปี", conf: "high" },
  { brand: "Mitsubishi Electric", series: "KA", warranty: "คอมเพรสเซอร์ 5 ปี · แผงคอยล์ร้อน-เย็น 3 ปี · อะไหล่ภายในตัวเครื่อง 1 ปี", conf: "high" },
  { brand: "Mitsubishi Electric", series: "M", warranty: "คอมเพรสเซอร์ 5 ปี · แผงคอยล์ร้อน-เย็น 3 ปี · อะไหล่ภายในตัวเครื่อง 1 ปี", conf: "high" },
  { brand: "Mitsubishi Electric", series: "PEY", warranty: "คอมเพรสเซอร์ 5 ปี · แผงคอยล์ร้อน-เย็น 3 ปี · อะไหล่ภายในตัวเครื่อง 1 ปี", conf: "high" },
  { brand: "Mitsubishi Electric", series: "PLY", warranty: "คอมเพรสเซอร์ 5 ปี · แผงคอยล์ร้อน-เย็น 3 ปี · อะไหล่ภายในตัวเครื่อง 1 ปี", conf: "high" },
  { brand: "Mitsubishi Electric", series: "SM", warranty: "คอมเพรสเซอร์ 5 ปี · แผงคอยล์ร้อน-เย็น 3 ปี · อะไหล่ภายในตัวเครื่อง 1 ปี", conf: "high" },
  { brand: "Mitsubishi Electric", series: "XZ", warranty: "คอมเพรสเซอร์ 5 ปี · แผงคอยล์ร้อน-เย็น 3 ปี · อะไหล่ภายในตัวเครื่อง 1 ปี", conf: "high" },
  { brand: "Mitsubishi Heavy Duty", series: "Cassette FDT", warranty: "คอมเพรสเซอร์ 5 ปี · อะไหล่ 5 ปี · ไม่รวมค่าบริการ/ค่าแรง", conf: "low" },
  { brand: "Mitsubishi Heavy Duty", series: "Ceiling FDE", warranty: "คอมเพรสเซอร์ 5 ปี · อะไหล่ 5 ปี · ไม่รวมค่าบริการ/ค่าแรง", conf: "low" },
  { brand: "Mitsubishi Heavy Duty", series: "Duty Fuyu", warranty: "คอมเพรสเซอร์ 5 ปี · อะไหล่ 5 ปี · ไม่รวมค่าบริการ/ค่าแรง", conf: "medium" },
  { brand: "Mitsubishi Heavy Duty", series: "Duty Haru", warranty: "คอมเพรสเซอร์ 5 ปี · อะไหล่ 5 ปี · ไม่รวมค่าบริการ/ค่าแรง", conf: "medium" },
  { brand: "Mitsubishi Heavy Duty", series: "Duty Hoshi", warranty: "คอมเพรสเซอร์ 5 ปี · อะไหล่ 5 ปี · ไม่รวมค่าบริการ/ค่าแรง", conf: "medium" },
  { brand: "Mitsubishi Heavy Duty", series: "Duty Kaze", warranty: "คอมเพรสเซอร์ 5 ปี · อะไหล่ 5 ปี · ไม่รวมค่าบริการ/ค่าแรง", conf: "medium" },
  { brand: "Mitsubishi Heavy Duty", series: "Duty Yuki", warranty: "คอมเพรสเซอร์ 5 ปี · อะไหล่ 5 ปี · ไม่รวมค่าบริการ/ค่าแรง", conf: "medium" },
  { brand: "Mitsubishi Heavy Duty", series: "FDUM", warranty: "คอมเพรสเซอร์ 5 ปี · อะไหล่ 5 ปี · ไม่รวมค่าบริการ/ค่าแรง", conf: "low" },
  { brand: "Mitsubishi Heavy Duty", series: "SRK", warranty: "คอมเพรสเซอร์ 5 ปี · อะไหล่ 5 ปี · ไม่รวมค่าบริการ/ค่าแรง", conf: "medium" },
  { brand: "Samsung", series: "360 CST", warranty: "คอมเพรสเซอร์ 10 ปี · แผงคอยล์ร้อน/เย็น 3 ปี · อะไหล่ 1 ปี · ฟรีค่าแรง 1 ปี (ยืนยันแน่นอนเฉพาะส่วน 'อะไหล่ 1 ปี + ฟรีค่าแรง/ค่าเดินทาง' — ตัวเลขคอมเพรสเซอร์/คอยล์ยังไม่มีแหล่งทางการรายซีรีส์ ควรยืนยันกับ Samsung ก่อนพิมพ์ผูกมัดลูกค้า)", conf: "low" },
  { brand: "Samsung", series: "AC", warranty: "คอมเพรสเซอร์ 10 ปี · แผงคอยล์ร้อน/เย็น 3 ปี · อะไหล่ 1 ปี · ฟรีค่าแรง 1 ปี (ยืนยันแน่นอนเฉพาะส่วน 'อะไหล่ 1 ปี + ฟรีค่าแรง/ค่าเดินทาง' — ตัวเลขคอมเพรสเซอร์/คอยล์ยังไม่มีแหล่งทางการรายซีรีส์ ควรยืนยันกับ Samsung ก่อนพิมพ์ผูกมัดลูกค้า)", conf: "low" },
  { brand: "Samsung", series: "AR", warranty: "คอมเพรสเซอร์ 10 ปี · แผงคอยล์ร้อน/เย็น 3 ปี · อะไหล่ 1 ปี · ฟรีค่าแรง 1 ปี (ลงทะเบียนภายใน 90 วันนับจากวันซื้อ ขยายคอยล์/อะไหล่/ค่าแรงเป็น 5 ปี — เฉพาะสินค้าที่ซื้อในช่วง 1 ม.ค.–31 ธ.ค. 2569 และเฉพาะรุ่นในลิสต์ 5 ปี เช่น AR80F/AR70/AR60 ส่วน AR50H/DYHZB/CYEC/CYHC ได้ 3 ปี)", conf: "high" },
  { brand: "Samsung", series: "Cassette WindFree", warranty: "คอมเพรสเซอร์ 10 ปี · แผงคอยล์ร้อน/เย็น 3 ปี · อะไหล่ 1 ปี · ฟรีค่าแรง 1 ปี (ยืนยันแน่นอนเฉพาะส่วน 'อะไหล่ 1 ปี + ฟรีค่าแรง/ค่าเดินทาง' — ตัวเลขคอมเพรสเซอร์/คอยล์ยังไม่มีแหล่งทางการรายซีรีส์ ควรยืนยันกับ Samsung ก่อนพิมพ์ผูกมัดลูกค้า)", conf: "low" },
  { brand: "Star aire", series: "Star DM", warranty: "คอมเพรสเซอร์ 10 ปี · อะไหล่ 2 ปี", conf: "high" },
  { brand: "Star aire", series: "Star FIV", warranty: "คอมเพรสเซอร์ 5 ปี · อะไหล่ 2 ปี (ใช้ได้เฉพาะรุ่น FIV แท้ 3 ขนาด: DM-095/125 FIV และ DM-185 FIVA เท่านั้น)", conf: "medium" },
  { brand: "TCL", series: "BreezeIN Premium", warranty: "คอมเพรสเซอร์ 10 ปี · อะไหล่ 5 ปี (เฉพาะซื้อผ่านช่องทางออฟไลน์จากตัวแทนจำหน่ายที่ได้รับแต่งตั้ง — ซื้อออนไลน์ คอมเพรสเซอร์ 5 ปี · อะไหล่ 1 ปี)", conf: "high" },
  { brand: "TCL", series: "BreezeIN WiFi", warranty: "คอมเพรสเซอร์ 10 ปี · อะไหล่ 5 ปี (เฉพาะซื้อผ่านช่องทางออฟไลน์จากตัวแทนจำหน่ายที่ได้รับแต่งตั้ง — ซื้อออนไลน์ คอมเพรสเซอร์ 5 ปี · อะไหล่ 1 ปี)", conf: "high" },
  { brand: "TCL", series: "CA", warranty: "คอมเพรสเซอร์ 10 ปี · อะไหล่ 5 ปี (เฉพาะซื้อผ่านช่องทางออฟไลน์จากตัวแทนจำหน่ายที่ได้รับแต่งตั้ง — ซื้อออนไลน์ คอมเพรสเซอร์ 5 ปี · อะไหล่ 1 ปี)", conf: "medium" },
  { brand: "TCL", series: "CE", warranty: "คอมเพรสเซอร์ 10 ปี · อะไหล่ 5 ปี (เฉพาะซื้อผ่านช่องทางออฟไลน์จากตัวแทนจำหน่ายที่ได้รับแต่งตั้ง — ซื้อออนไลน์ คอมเพรสเซอร์ 5 ปี · อะไหล่ 1 ปี)", conf: "medium" },
  { brand: "TCL", series: "SaveIN F1", warranty: "คอมเพรสเซอร์ 10 ปี · อะไหล่ 5 ปี (เฉพาะซื้อผ่านช่องทางออฟไลน์จากตัวแทนจำหน่ายที่ได้รับแต่งตั้ง — ซื้อออนไลน์ คอมเพรสเซอร์ 5 ปี · อะไหล่ 1 ปี)", conf: "high" },
  { brand: "TCL", series: "TAC", warranty: "คอมเพรสเซอร์ 10 ปี · อะไหล่ 5 ปี (เฉพาะซื้อผ่านช่องทางออฟไลน์จากตัวแทนจำหน่ายที่ได้รับแต่งตั้ง — ซื้อออนไลน์ คอมเพรสเซอร์ 5 ปี · อะไหล่ 1 ปี)", conf: "medium" },
  { brand: "TCL", series: "TCL SaveIN", warranty: "คอมเพรสเซอร์ 10 ปี · อะไหล่ 5 ปี (เฉพาะซื้อผ่านช่องทางออฟไลน์จากตัวแทนจำหน่ายที่ได้รับแต่งตั้ง — ซื้อออนไลน์ คอมเพรสเซอร์ 5 ปี · อะไหล่ 1 ปี)", conf: "high" },
  { brand: "TCL", series: "TCL VOXIN", warranty: "คอมเพรสเซอร์ 10 ปี · อะไหล่ 5 ปี (เฉพาะซื้อผ่านช่องทางออฟไลน์จากตัวแทนจำหน่ายที่ได้รับแต่งตั้ง — ซื้อออนไลน์ คอมเพรสเซอร์ 5 ปี · อะไหล่ 1 ปี)", conf: "high" },
];
