-- 107_ac_media_links.sql — รูปสินค้า + โบรชัวร์รุ่น จากเว็บผู้ผลิต/ตัวแทนทางการ (ตรวจลิงก์แล้ว 192/192)
-- รูป: ใส่เฉพาะตัวที่ยังไม่มีรูป (ไม่ทับรูปที่ถ่ายเอง) · โบรชัวร์: ใส่เฉพาะรุ่นที่ยังว่าง
-- Central Air ไม่อยู่ในชุดนี้ (เว็บเขาใช้ http:// เท่านั้น จะโดนเบราว์เซอร์บล็อกบนเว็บ https เรา — ใช้ปุ่ม 🔗 ดึงจากลิงก์แทน)
-- รันใน Supabase → SQL Editor (ครั้งเดียว)

-- 1) รูปสินค้า — แอร์ทุกขนาดในรุ่นเดียวกันใช้รูปรุ่น
update materials m set photo_url = v.img
from (values
  ('Gree', 'Gree SAVI', 'https://www.greethailand.com/img/upload/Savi%20%20%E0%B8%95%E0%B8%A3%E0%B8%87%20%20(800%20%C3%97%20600px).png'),
  ('Gree', 'PULAR I1', 'https://dasintergroup.com/daswp/wp-content/uploads/2022/02/Gree-Pular-I1-Series.jpg'),
  ('Gree', 'Cap', 'https://www.greethailand.com/img/upload/Hi-Cap%20%E0%B8%95%E0%B8%A3%E0%B8%87%20(800%20%C3%97%20600px).png'),
  ('TCL', 'BreezeIN Premium', 'https://aws-obg-image-lb-1.tcl.com/content/dam/brandsite/region/thailand/product/air-conditioner/breezein-premium/image/1.png'),
  ('TCL', 'BreezeIN WiFi', 'https://aws-obg-image-lb-1.tcl.com/content/dam/brandsite/region/thailand/product/air-conditioner/breezein-wifi/image/1.png'),
  ('TCL', 'TCL SaveIN', 'https://aws-obg-image-lb-1.tcl.com/content/dam/brandsite/region/thailand/product/air-conditioner/savein-series/image/1.png'),
  ('TCL', 'SaveIN F1', 'https://aws-obg-image-lb-1.tcl.com/content/dam/brandsite/region/thailand/product/air-conditioner/savein-f1-series/image/1.png'),
  ('TCL', 'TCL VOXIN', 'https://aws-obg-image-lb-1.tcl.com/content/dam/brandsite/region/thailand/product/air-conditioner/voxin/image/1.png'),
  ('TCL', 'TAC', 'https://aws-obg-image-lb-1.tcl.com/content/dam/brandsite/region/thailand/product/ac/miracle-series/product-image/01.png'),
  ('TCL', 'CA', 'https://aws-obg-image-lb-1.tcl.com/content/dam/brandsite/region/thailand/product/air-conditioner/cac/image/1.png'),
  ('TCL', 'CE', 'https://aws-obg-image-lb-1.tcl.com/content/dam/brandsite/region/thailand/product/air-conditioner/ceiling-cooling/image/1.png'),
  ('Midea', 'Midea Celest', 'https://web-res.midea.com/content/dam/midea-aem/th/air-conditioners/residential-air-conditioner/celest-inverter/Celest-Inverter-03.jpg/jcr:content/renditions/Celest-Inverter-03.webp'),
  ('Midea', 'Midea Numen', 'https://web-res.midea.com/content/dam/midea-aem/th/th-new/pdp/air-conditioner/residential/single-split/msne-10crfn8-id-msne-10crfn8-od/Numen-Inverter-front-on-new.jpg/jcr:content/renditions/Numen-Inverter-front-on-new.webp'),
  ('Midea', 'MSEPB', 'https://web-res.midea.com/content/dam/midea-aem/th/air-conditioners/residential-air-conditioner/inverter-ac/msfaau-09hrfn8-qrd6gw/mpro-easy-inverter-01-new.jpg/jcr:content/renditions/mpro-easy-inverter-01-new.webp'),
  ('Midea', 'MSEPC', 'https://web-res.midea.com/content/dam/midea-aem/th/th-new/pdp/air-conditioner/residential/single-split/msepc-24crfn8-qd3w/mpro-easy-inverter-01-new.jpg/jcr:content/renditions/mpro-easy-inverter-01-new.webp'),
  ('Midea', 'Torndo Easy', 'https://web-res.midea.com/content/dam/midea-aem/th/th-new/pdp/air-conditioner/residential/single-split/msag-09crn8-idu/Tornado-Easy-front-on-new.jpg/jcr:content/renditions/Tornado-Easy-front-on-new.webp'),
  ('Midea', 'Cassette LCAC', 'https://web-res.midea.com/content/dam/midea-aem/th/th-new/pdp/air-conditioner/commercial/cassette/01-Air-conditioner-03-LCAC-Light-commercial-air-conditioner-02-4-WaysCassette-MCD-40CRN1-PC4-Front-new.jpg/jcr:content/renditions/01-Air-conditioner-03-LCAC-Light-commercial-air-conditioner-02-4-WaysCassette-MCD-40CRN1-PC4-Front-new.webp'),
  ('Midea', 'Ceiling LCAC', 'https://web-res.midea.com/content/dam/midea-aem/th/th-new/pdp/air-conditioner/commercial/ceiling-floor/mue-36crdn8-r/gallery1-new.jpg/jcr:content/renditions/gallery1-new.webp'),
  ('Midea', 'Ceiling ME', 'https://web-res.midea.com/content/dam/midea-aem/th/th-new/pdp/air-conditioner/commercial/ceiling-floor/me-24crn8-pc5-md30u-24cn8-pc5/Ceiling-01-new.jpg/jcr:content/renditions/Ceiling-01-new.webp'),
  ('Midea', 'MTI', 'https://web-res.midea.com/content/dam/midea-aem/th/th-new/pdp/air-conditioner/commercial/ceiling-floor/mti-30hwfnx-qrd0w(ga)-mod30u-30hfn8-qrd0w(ga)/duct-01-new.jpg/jcr:content/renditions/duct-01-new.webp'),
  ('Midea', 'MTIU', 'https://web-res.midea.com/content/dam/midea-aem/th/th-new/pdp/air-conditioner/commercial/ducted/mtiu-18hwfnx-qrd0w/01-Air-conditioner-03-LCAC-Light-commercial-air-conditioner-03-Duct-Front-new.jpg/jcr:content/renditions/01-Air-conditioner-03-LCAC-Light-commercial-air-conditioner-03-Duct-Front-new.webp'),
  ('Midea', 'MFGA', 'https://web-res.midea.com/content/dam/midea-aem/th/th-new/pdp/air-conditioner/commercial/standing/mfga-60crn1-r-m/01-Air-conditioner-03-LCAC-Light-commercial-air-conditioner-04-FloorStanding-LCAC-CA-front-new.jpg/jcr:content/renditions/01-Air-conditioner-03-LCAC-Light-commercial-air-conditioner-04-FloorStanding-LCAC-CA-front-new.webp'),
  ('Midea', 'MFJ', 'https://web-res.midea.com/content/dam/midea-aem/th/th-new/pdp/air-conditioner/commercial/standing/mfj-48crn1-q-mod3/01-Air-conditioner-03-LCAC-Light-commercial-air-conditioner-04-FloorStanding-LCAC-CA-front-new.jpg/jcr:content/renditions/01-Air-conditioner-03-LCAC-Light-commercial-air-conditioner-04-FloorStanding-LCAC-CA-front-new.webp'),
  ('Midea', 'MFTM', 'https://web-res.midea.com/content/dam/midea-aem/th/th-new/pdp/air-conditioner/commercial/ceiling-floor/mftm-36hrn1-qb8id-motdul-36hn1-q0d/floor-standing-01-new.jpg/jcr:content/renditions/floor-standing-01-new.webp'),
  ('Star aire', 'Star DM', 'https://image.makewebeasy.net/makeweb/m_1920x0/zExDZmdGh/product/DM125A__New_No_5__1.png'),
  ('Star aire', 'Star FIV', 'https://image.makewebeasy.net/makeweb/m_1920x0/zExDZmdGh/product/DM_125IV.png'),
  ('Samsung', 'AR', 'https://images.samsung.com/is/image/samsung/p6pim/th/f-ar50h09d1chn/gallery/th-wall-mount-f-ar50h09d1chn-ar--h--d-chnst-white-551031494?$1164_776_PNG$'),
  ('Samsung', 'Cassette WindFree', 'https://images.samsung.com/is/image/samsung/p6pim/th/f-ac071-4w1std/gallery/th-ceiling-air-conditioner-f-ac071-4w1std----------------539194397?$1164_776_PNG$'),
  ('Samsung', '360 CST', 'https://images.samsung.com/is/image/samsung/p6pim/th/f-ac071-sw1std/gallery/th-ceiling-air-conditioner-f-ac071-sw1std----------------539183915?$1164_776_PNG$'),
  ('Samsung', 'AC', 'https://images.samsung.com/is/image/samsung/p6pim/th/f-ac071-1w1-st/gallery/th-ceiling-air-conditioners-f-ac071-1w1-st-f-ac071-1w1-st-535216382?$1164_776_PNG$'),
  ('LG', 'VICTORY IKR', 'https://www.lg.com/content/dam/channel/wcms/th/image-update/air-conditioner/2025/image-with-icon/ikr/RAC2025-Web-Thumbnail_IKR-2010x1334.jpg'),
  ('LG', 'Cassette ZTNQ', 'https://www.lg.com/content/dam/channel/wcms/th/hvac/zt-q18gple0/2025/th/gp1/gallery/01-basic/lg-four-way-ceiling-cassette-2025-basic-large.jpg'),
  ('LG', 'Ceiling ZVNQ', 'https://www.lg.com/content/dam/channel/wcms/th/hvac/zv-q18gm1e0/2025/th/gp1/gallery/01-basic/lg-ceiling-suspended-2025-basic-large.jpg'),
  ('Daikin', 'Cassette FCC', 'https://daikin.co.th/assets/uploads/product/23/product_image/fcc-avatar.jpg'),
  ('Daikin', 'Ceiling FHA', 'https://daikin.co.th/assets/uploads/product/16/product_image/fha-avatar.jpg'),
  ('Daikin', 'Ceiling FHFC', 'https://daikin.co.th/assets/uploads/product/18/product_image/fhfc-avatar.jpg'),
  ('Daikin', 'Ceiling FHNQ', 'https://daikin.co.th/assets/uploads/product/24/product_image/fhnq.jpg'),
  ('Daikin', 'Daikin FTM', 'https://daikin.co.th/assets/uploads/product/60/product_image/ftm-avatar.jpg'),
  ('Daikin', 'FBA', 'https://daikin.co.th/assets/uploads/product/15/product_image/fba-avatar.jpg'),
  ('Daikin', 'FBFC', 'https://daikin.co.th/assets/uploads/product/19/product_image/fbfc-avatar.jpg'),
  ('Daikin', 'FCF', 'https://daikin.co.th/assets/uploads/product/14/product_image/fcf-avatar.jpg'),
  ('Daikin', 'FCFC', 'https://daikin.co.th/assets/uploads/product/17/product_image/fcfc-avatar.jpg'),
  ('Daikin', 'FCTF', 'https://daikin.co.th/assets/uploads/product/13/product_image/fctf-avatar.jpg'),
  ('Daikin', 'FDBF', 'https://daikin.co.th/assets/uploads/product/20/product_image/fdbf-avatar.jpg'),
  ('Daikin', 'STAR FAVF', 'https://daikin.co.th/assets/uploads/product/61/product_image/favf-avatar.jpg'),
  ('Daikin', 'STAR KB', 'https://daikin.co.th/assets/uploads/product/131/product_image/ftkq-avatar.jpg'),
  ('Daikin', 'STAR KF', 'https://daikin.co.th/assets/uploads/product/58/product_image/ftkf-avatar.jpg'),
  ('Daikin', 'STAR KM', 'https://daikin.co.th/assets/uploads/product/56/product_image/ftkm-y-avatar.jpg'),
  ('Daikin', 'STAR KQ', 'https://daikin.co.th/assets/uploads/product/59/product_image/ftkq-avatar.jpg'),
  ('Daikin', 'STAR KZ', 'https://daikin.co.th/assets/uploads/product/55/product_image/ftkzy-avatar.png'),
  ('Mitsubishi Electric', 'AW', 'https://www.mitsubishi-kyw.co.th/getattachment/Product/For-Home/conditioner/LN-Serie/1088-(2)/AW-Series-01.jpg.aspx'),
  ('Mitsubishi Electric', 'GY', 'https://www.mitsubishi-kyw.co.th/getattachment/Product/For-Home/conditioner/Econo/Econo-Air/Econo-Air-09-01.jpg.aspx'),
  ('Mitsubishi Electric', 'GZ', 'https://www.mitsubishi-kyw.co.th/getattachment/Product/For-Home/conditioner/GT-Series/1106/GZ-09-Front-1.jpg.aspx'),
  ('Mitsubishi Electric', 'JY', 'https://www.mitsubishi-kyw.co.th/getattachment/Product/For-Home/conditioner/JS-Series/Wide-Long/JY36-01.jpg.aspx'),
  ('Mitsubishi Electric', 'JZ', 'https://www.mitsubishi-kyw.co.th/getattachment/Product/For-Home/conditioner/JS-Series/Super-Inverter-(1)/JZ09_1Fornt.jpg.aspx'),
  ('Mitsubishi Electric', 'KA', 'https://www.mitsubishi-kyw.co.th/getattachment/Product/For-Home/conditioner/KT-Series/5527/MSY-KA_09side1.jpg.aspx'),
  ('Mitsubishi Electric', 'XZ', 'https://www.mitsubishi-kyw.co.th/getattachment/Product/For-Home/conditioner/XT-Serie/Super-Inverter-(6)/XZ09-Front-01-(1).jpg.aspx'),
  ('Mitsubishi Electric', 'Cassette PL', 'https://www.mitsubishi-kyw.co.th/getattachment/Product/For-Home/conditioner/PL-Series/1253-(1)/PLY-PL-Series_move-eye-(1).jpg.aspx'),
  ('Mitsubishi Electric', 'PLY', 'https://www.mitsubishi-kyw.co.th/getattachment/Product/For-Home/conditioner/PLY-Series/4156/01-PLY-PL-Series.jpg.aspx'),
  ('Mitsubishi Electric', 'M', 'https://www.mitsubishi-kyw.co.th/getattachment/Product/For-Home/conditioner/PC-Series/1258/PCY_PC-Series-(1).jpg.aspx'),
  ('Mitsubishi Electric', 'SM', 'https://www.mitsubishi-kyw.co.th/getattachment/Product/For-Home/conditioner/PCY-Series/5768/1-PCY_PC-Series.jpg.aspx'),
  ('Mitsubishi Electric', 'PEY', 'https://www.mitsubishi-kyw.co.th/getattachment/Product/For-Home/conditioner/PEY-Series/1249-(1)/1-PEY_PE-Series.jpg.aspx'),
  ('Mitsubishi Electric', 'SE', 'https://www.mitsubishi-kyw.co.th/getattachment/Product/For-Home/conditioner/PE-Series/1264-(3)/PEY_PE-Series-(1).jpg.aspx'),
  ('Mitsubishi Heavy Duty', 'Duty Fuyu', 'https://www.mitsuheavythai.com/backoffice/uploads/eventThumbm1020180710100338.png'),
  ('Mitsubishi Heavy Duty', 'Duty Haru', 'https://www.mitsuheavythai.com/backoffice/uploads/eventThumbm1020240911044041.png'),
  ('Mitsubishi Heavy Duty', 'Duty Hoshi', 'https://www.mitsuheavythai.com/backoffice/uploads/eventThumbm1020230519063525.png'),
  ('Mitsubishi Heavy Duty', 'Duty Kaze', 'https://www.mitsuheavythai.com/backoffice/uploads/eventThumbm1020251212041519.png'),
  ('Mitsubishi Heavy Duty', 'Duty Yuki', 'https://www.mitsuheavythai.com/backoffice/uploads/eventThumbm1020230808064228.png'),
  ('Mitsubishi Heavy Duty', 'SRK', 'https://www.mitsuheavythai.com/backoffice/uploads/eventThumbm1020250407031025.png'),
  ('Mitsubishi Heavy Duty', 'Cassette FDT', 'https://www.mitsuheavythai.com/backoffice/uploads/eventThumbm1020211118102914.png'),
  ('Mitsubishi Heavy Duty', 'Ceiling FDE', 'https://www.mitsuheavythai.com/backoffice/uploads/eventThumbm1020211118104206.jpg'),
  ('Mitsubishi Heavy Duty', 'FDUM', 'https://www.mitsuheavythai.com/backoffice/uploads/eventThumbm1020211118105202.jpg'),
  ('Carrier', 'TVAB', 'https://images.carriercms.com/image/upload/v1676470545/carrier/hvac-thailand/products/residential/carrier-42TVAB-fancoil.jpg'),
  ('Carrier', 'TVDB', 'https://images.carriercms.com/image/upload/v1770323415/carrier/hvac-thailand/products/residential/Copper_Seal_Inverter_Hi-wall.png'),
  ('Carrier', 'TVEB', 'https://images.carriercms.com/image/upload/v1770323415/carrier/hvac-thailand/products/residential/Copper_ION_Inverter_Hi-wall.png'),
  ('Carrier', 'TSAA', 'https://images.carriercms.com/image/upload/v1676470516/carrier/hvac-thailand/products/residential/carrier-42TSAA-fancoil.jpg'),
  ('Carrier', 'NSAA', 'https://images.carriercms.com/image/upload/v1770323415/carrier/hvac-thailand/products/residential/TECH-S_Fix_Speed_Hi-wall.png'),
  ('Carrier', 'NVAA', 'https://images.carriercms.com/image/upload/v1770323415/carrier/hvac-thailand/products/residential/TECH-V_Inverter_Hi-wall.png'),
  ('Carrier', 'Apollo lll', 'https://ttair.co.th/wp-content/uploads/2025/06/Carrier-Floor-Ceiling-APOLLO-III-42FGE.jpg'),
  ('Carrier', 'Ceiling TGF', 'https://carrierthailand.com/wp-content/uploads/2023/02/Discovery_Ceiling.jpg'),
  ('Carrier', 'Ceiling TGV', 'https://carrierthailand.com/wp-content/uploads/2023/02/XPower_Ceiling.jpg'),
  ('Carrier', 'Ceiling TGEV', 'https://images.carriercms.com/image/upload/v1709218101/carrier/commercial-hvac-asia/products/split-type/42TGF-CP/UC_42TGF.jpg'),
  ('Carrier', 'Cassette TGF', 'https://images.carriercms.com/image/upload/v1702653479/carrier/commercial-hvac-asia/products/split-type/40TGF-UP/Smart-4-way_carrier.jpg'),
  ('Carrier', 'Cassette TGV', 'https://images.carriercms.com/image/upload/v1702653367/carrier/commercial-hvac-asia/products/split-type/40TGV-UP/Smart-4-way_carrier.jpg'),
  ('Carrier', 'Cassette TGEV', 'https://images.carriercms.com/image/upload/v1727864406/carrier/hvac-thailand/products/light-commercial/cassette/40TGEV024-0481UP.jpg'),
  ('Carrier', 'Cassette VLJ', 'https://images.carriercms.com/image/upload/v1709207370/carrier/commercial-hvac-asia/products/split-type/40VLJ-40VLY-series/4W_40VLJ.jpg'),
  ('Carrier', 'Way TGF', 'https://carrierthailand.com/wp-content/uploads/2026/01/Discovery-Cassette-1-way-jpg.webp'),
  ('Carrier', 'Way TGV', 'https://images.carriercms.com/image/upload/v1676054271/carrier/hvac-thailand/products/light-commercial/cassette/carrier-40BGV-fancoil.jpg'),
  ('Carrier', 'TGF', 'https://images.carriercms.com/image/upload/v1702653997/carrier/commercial-hvac-asia/products/split-type/42TGF-BP/Standard-Duct-2.jpg'),
  ('Carrier', 'TGV', 'https://images.carriercms.com/image/upload/v1710164709/carrier/commercial-hvac-asia/products/split-type/42TGV-BP/Standard_Duct.jpg'),
  ('Carrier', '40QBU', 'https://images.carriercms.com/image/upload/v1676469784/carrier/hvac-thailand/products/light-commercial/floor-standing/carrier-40QBY-fancoil.jpg'),
  ('Carrier', 'Standing 40QGF', 'https://ttair.co.th/wp-content/uploads/2026/01/Carrier-Floor-Standing-Type-TGF-40QGF.jpg'),
  ('Haier', 'HSU', 'https://image.haier.com/th/air-conditioners/W020240227687551096793_480.jpg'),
  ('Haier', 'Cool Plus', 'https://dasintergroup.com/daswp/wp-content/uploads/2022/01/Haier-Gale-Cool-Plus-Premium-Ceiling-Type-Series.jpg'),
  ('Haier', 'Ceiling HCFU', 'https://dasintergroup.com/daswp/wp-content/uploads/2022/01/Haier-Gale-Cool-Plus-Premium-Ceiling-Type-Series.jpg'),
  ('Haier', 'Flow HCSI', 'https://dasintergroup.com/daswp/wp-content/uploads/2023/12/premium-inverter-cassette-type-series.jpg'),
  ('Haier', 'Flow HCSU', 'https://dasintergroup.com/daswp/wp-content/uploads/2024/01/Haier-SuperAir-2023-HCSU-Series.jpg'),
  ('Haier', 'Way HCS1', 'https://dasintergroup.com/daswp/wp-content/uploads/2024/04/Haier-1-way-casette-type-series.jpg'),
  ('Haier', 'HDI', 'https://image.haier.com/th/commercial-air-conditioners/W020220421612889148073_480.jpg'),
  ('Hisense', 'Hisense KC', 'https://hisense.co.th/img/products/gallery/NDIxMDQwNDI/a3a56914986d53cefc4728102a9a0a1b.jpg'),
  ('Hisense', 'Hisense KD', 'https://media.bbairtrading.com/2026/03/1-01-01-6-scaled.png'),
  ('Hisense', 'Cassette Mark5', 'https://dasintergroup.com/daswp/wp-content/uploads/2022/01/Hisense-Mark5-Cassette-Type-Series.jpg'),
  ('Hisense', 'Floor', 'https://dasintergroup.com/daswp/wp-content/uploads/2024/07/Hisense-Mark-5-Ceiling-Floor-Type-Series.jpg'),
  ('AUX', 'AUX MA', 'https://mws-data.auxair.com/upload/2025-01-13/1736760393720_7ac80780-d190-11ef-adb7-b572d61b301f.png'),
  ('AUX', 'AUX MF', 'https://image.makewebcdn.com/makeweb/m_1920x0/aakL1iErY/AUX_ASW_DIMA_3S/AUX_ASW_DIMA_3S_001.jpg')
) as v(brand, series, img)
where m.kind = 'ac' and coalesce(m.brand, '') = v.brand and m.series = v.series
  and (m.photo_url is null or m.photo_url = '');

-- 2) โบรชัวร์ของรุ่น
update ac_series s set brochure_url = v.url
from (values
  ('Gree', 'Gree SAVI', 'https://www.greethailand.com/img/file_upload/savi-new67_updated.pdf'),
  ('Gree', 'PULAR I1', 'https://dasintergroup.com/daswp/wp-content/uploads/2022/02/Gree-pular-i1-Series-Brochure.pdf'),
  ('Gree', 'Cap', 'https://www.greethailand.com/img/file_upload/Highcap67_updated.pdf'),
  ('Star aire', 'Star DM', 'https://image.makewebeasy.net/makeweb/0/zExDZmdGh/Document/2026_1_DM_A_compressed.pdf'),
  ('Star aire', 'Star FIV', 'https://image.makewebeasy.net/makeweb/0/zExDZmdGh/Document/2026_3_DM_IV_compressed.pdf'),
  ('Samsung', 'AR', 'https://org.downloadcenter.samsung.com/downloadfile/ContentsFile.aspx?CDSite=UNI_TH&OriginYN=N&ModelType=N&ModelName=AR50H09D1CHNST&CttFileID=11222840&CDCttType=UM&VPath=UM%2F202512%2F20251225153720176%2FRAC237-00_IB_26Y_AR9500T_Wind_GEO_ST_TH-WEB_251029-D03.pdf'),
  ('LG', 'Cassette ZTNQ', 'https://www.lg.com/content/dam/channel/wcms/th/business/download/resources/ct40004201/04-4%20Way%20Cassette-01_20240816_194731_.pdf'),
  ('LG', 'Ceiling ZVNQ', 'https://www.lg.com/content/dam/channel/wcms/th/pdf/2024/catalog/september/Aw_NW_Catalogue_Issue_2(Preview).pdf'),
  ('Daikin', 'Cassette FCC', 'https://www.daikincatalog.com/library/books/sds_0028/book/data/all_page.pdf'),
  ('Daikin', 'Ceiling FHA', 'https://www.daikincatalog.com/library/books/sds_0016/book/data/all_page.pdf'),
  ('Daikin', 'Ceiling FHFC', 'https://www.daikincatalog.com/library/books/sds_0030/book/data/all_page.pdf'),
  ('Daikin', 'Ceiling FHNQ', 'https://www.daikincatalog.com/library/books/sds_0028/book/data/all_page.pdf'),
  ('Daikin', 'Daikin FTM', 'https://www.daikincatalog.com/library/books/sds_0007/book/data/all_page.pdf'),
  ('Daikin', 'FBA', 'https://www.daikincatalog.com/library/books/sds_0016/book/data/all_page.pdf'),
  ('Daikin', 'FBFC', 'https://www.daikincatalog.com/library/books/sds_0030/book/data/all_page.pdf'),
  ('Daikin', 'FCF', 'https://www.daikincatalog.com/library/books/sds_0016/book/data/all_page.pdf'),
  ('Daikin', 'FCFC', 'https://www.daikincatalog.com/library/books/sds_0030/book/data/all_page.pdf'),
  ('Daikin', 'FCTF', 'https://www.daikincatalog.com/library/books/sds_0016/book/data/all_page.pdf'),
  ('Daikin', 'FDBF', 'https://www.daikincatalog.com/library/books/sds_0030/book/data/all_page.pdf'),
  ('Daikin', 'STAR FAVF', 'https://www.daikincatalog.com/library/books/sds_0014/book/data/all_page.pdf'),
  ('Daikin', 'STAR KB', 'https://www.daikincatalog.com/library/books/sds_0051/book/data/all_page.pdf'),
  ('Daikin', 'STAR KF', 'https://www.daikincatalog.com/library/books/sds_0032/book/data/all_page.pdf'),
  ('Daikin', 'STAR KM', 'https://www.daikincatalog.com/library/books/sds_0033/book/data/all_page.pdf'),
  ('Daikin', 'STAR KQ', 'https://www.daikincatalog.com/library/books/sds_0034/book/data/all_page.pdf'),
  ('Daikin', 'STAR KZ', 'https://www.daikincatalog.com/library/books/sds_0035/book/data/all_page.pdf'),
  ('Mitsubishi Electric', 'AW', 'https://www.mitsubishi-kyw.co.th/getattachment/Product/For-Home/conditioner/LN-Serie/1088-(2)/Catalog-RAC-2026.pdf.aspx'),
  ('Mitsubishi Electric', 'GY', 'https://www.mitsubishi-kyw.co.th/getattachment/Product/For-Home/conditioner/Econo/Econo-Air/One-sheet-Econo-2026.pdf.aspx'),
  ('Mitsubishi Electric', 'GZ', 'https://www.mitsubishi-kyw.co.th/getattachment/Product/For-Home/conditioner/GT-Series/1106/Catalog-RAC-2026.pdf.aspx'),
  ('Mitsubishi Electric', 'JY', 'https://www.mitsubishi-kyw.co.th/getattachment/Product/For-Home/conditioner/JS-Series/Wide-Long/Catalog-RAC-2026.pdf.aspx'),
  ('Mitsubishi Electric', 'JZ', 'https://www.mitsubishi-kyw.co.th/getattachment/Product/For-Home/conditioner/JS-Series/Super-Inverter-(1)/Catalog-RAC-2026.pdf.aspx'),
  ('Mitsubishi Electric', 'KA', 'https://www.mitsubishi-kyw.co.th/getattachment/Product/For-Home/conditioner/KT-Series/5527/Catalog-RAC-2026.pdf.aspx'),
  ('Mitsubishi Electric', 'XZ', 'https://www.mitsubishi-kyw.co.th/getattachment/Product/For-Home/conditioner/XT-Serie/Super-Inverter-(6)/Catalog-RAC-2026.pdf.aspx'),
  ('Mitsubishi Electric', 'Cassette PL', 'https://www.mitsubishi-kyw.co.th/getattachment/Product/For-Home/conditioner/PL-Series/1253-(1)/Catalog-Mr-Slim-NON-SERIES-2026.pdf.aspx'),
  ('Mitsubishi Electric', 'PLY', 'https://www.mitsubishi-kyw.co.th/getattachment/Product/For-Home/conditioner/PLY-Series/4156/Catalog-Mr-Slim-SM-SERIES-2026.pdf.aspx'),
  ('Mitsubishi Electric', 'M', 'https://www.mitsubishi-kyw.co.th/getattachment/Product/For-Home/conditioner/PC-Series/1258/Catalog-Mr-Slim-NON-SERIES-2026.pdf.aspx'),
  ('Mitsubishi Electric', 'SM', 'https://www.mitsubishi-kyw.co.th/getattachment/Product/For-Home/conditioner/PCY-Series/5768/Catalog-Mr-Slim-M-SERIES-2026.pdf.aspx'),
  ('Mitsubishi Electric', 'PEY', 'https://www.mitsubishi-kyw.co.th/getattachment/Product/For-Home/conditioner/PEY-Series/1249-(1)/Catalog-Mr-Slim-SM-SERIES-2026.pdf.aspx'),
  ('Mitsubishi Electric', 'SE', 'https://www.mitsubishi-kyw.co.th/getattachment/Product/For-Home/conditioner/PE-Series/2624/Catalog-Mr-Slim-NON-SERIES-2026.pdf.aspx'),
  ('Mitsubishi Heavy Duty', 'Duty Fuyu', 'https://www.mitsuheavythai.com/backoffice/uploads/eventThumbm520260616032314.pdf'),
  ('Mitsubishi Heavy Duty', 'Duty Haru', 'https://www.mitsuheavythai.com/backoffice/uploads/eventThumbm520260616030434.pdf'),
  ('Mitsubishi Heavy Duty', 'Duty Hoshi', 'https://www.mitsuheavythai.com/backoffice/uploads/eventThumb1m120260616025209.pdf'),
  ('Mitsubishi Heavy Duty', 'Duty Kaze', 'https://www.mitsuheavythai.com/backoffice/uploads/eventThumb1m120260616024448.pdf'),
  ('Mitsubishi Heavy Duty', 'Duty Yuki', 'https://www.mitsuheavythai.com/backoffice/uploads/eventThumbm220260616030901.pdf'),
  ('Mitsubishi Heavy Duty', 'SRK', 'https://www.mitsuheavythai.com/backoffice/uploads/eventThumb1m120260616030234.pdf'),
  ('Mitsubishi Heavy Duty', 'Cassette FDT', 'https://www.mhi.com/group/maco/products/downloads/pdf/fd_series_asia_2022.pdf'),
  ('Mitsubishi Heavy Duty', 'Ceiling FDE', 'https://www.mhi.com/group/maco/products/downloads/pdf/fd_series_asia_2022.pdf'),
  ('Mitsubishi Heavy Duty', 'FDUM', 'https://www.mitsuheavythai.com/backoffice/uploads/eventThumbm320230426043725.pdf'),
  ('Carrier', 'TVAB', 'https://carrierthailand.com/wp-content/uploads/2026/04/Catalog_XInverter-Plus.pdf'),
  ('Carrier', 'TVDB', 'https://carrierthailand.com/wp-content/uploads/2026/04/Catalog_CopperSEAL.pdf'),
  ('Carrier', 'TVEB', 'https://carrierthailand.com/wp-content/uploads/2026/04/Catalog_CopperION-2026.pdf'),
  ('Carrier', 'TSAA', 'https://carrierthailand.com/wp-content/uploads/2025/04/COPPER7_2025.pdf'),
  ('Carrier', 'NSAA', 'https://carrierthailand.com/wp-content/uploads/2026/05/PDF-Catalog-TECH-VTECH-S-2026.pdf'),
  ('Carrier', 'NVAA', 'https://carrierthailand.com/wp-content/uploads/2026/05/PDF-Catalog-TECH-VTECH-S-2026.pdf'),
  ('Carrier', 'Apollo lll', 'https://carrierthailand.com/wp-content/uploads/2025/04/Apollo3_RGB.pdf'),
  ('Carrier', 'Ceiling TGF', 'https://carrierthailand.com/wp-content/uploads/2023/06/TGF_CP.pdf'),
  ('Carrier', 'Ceiling TGV', 'https://carrierthailand.com/wp-content/uploads/2022/02/xpower-tgv_cp.pdf'),
  ('Carrier', 'Ceiling TGEV', 'https://ttair.co.th/wp-content/uploads/2024/11/catalog-Carrier-X-POWER-TGEV-Series-2024.pdf'),
  ('Carrier', 'Cassette TGF', 'https://carrierthailand.com/wp-content/uploads/2023/06/TGF_UP.pdf'),
  ('Carrier', 'Cassette TGV', 'https://media.bbairtrading.com/2020/11/xpower-tgv_up-2022-CATALOG.pdf'),
  ('Carrier', 'Cassette TGEV', 'https://ttair.co.th/wp-content/uploads/2024/11/catalog-Carrier-X-POWER-TGEV-Series-2024.pdf'),
  ('Carrier', 'Cassette VLJ', 'https://media.bbairtrading.com/2022/09/40VLJ5_VLY-2022-CATALOG.pdf'),
  ('Carrier', 'Way TGF', 'https://media.bbairtrading.com/2023/03/40BGF-2023-CATALOG.pdf'),
  ('Carrier', 'Way TGV', 'https://media.bbairtrading.com/2020/11/BGV-UP-CATALOG-.pdf'),
  ('Carrier', 'TGF', 'https://carrierthailand.com/wp-content/uploads/2023/06/TGF_BP.pdf'),
  ('Carrier', 'TGV', 'https://media.bbairtrading.com/2022/10/TGV_Inverter-catalog-2024_new.pdf'),
  ('Carrier', '40QBU', 'https://media.bbairtrading.com/2023/08/40QBG_QBU_catalog-2023-CATALOG-1.pdf'),
  ('Haier', 'HSU', 'https://dasintergroup.com/daswp/wp-content/uploads/2024/01/Haier-UV-Cool-Premuim-Series-Brochure.pdf'),
  ('Haier', 'Cool Plus', 'https://www.modernair.com/media/advancedbundles/download/h/a/haier_ceiling_type_gale_cool_plus_premium_inverter_hcfi-psr32_.pdf'),
  ('Haier', 'Ceiling HCFU', 'https://dasintergroup.com/daswp/wp-content/uploads/2023/06/Haier-HCFU-A-Class-Series-Brochure.pdf'),
  ('Haier', 'Flow HCSI', 'https://dasintergroup.com/daswp/wp-content/uploads/2023/12/premium-inverter-cassette-type-series-Brochure.pdf'),
  ('Haier', 'Flow HCSU', 'https://dasintergroup.com/daswp/wp-content/uploads/2024/01/Haier-HCSU-Series-Brochure.pdf'),
  ('Haier', 'Way HCS1', 'https://dasintergroup.com/daswp/wp-content/uploads/2024/04/Haier-1-way-cassette-type-Brochure.pdf'),
  ('Haier', 'HDI', 'https://dasintergroup.com/daswp/wp-content/uploads/2022/12/Haier-HDI-Series-Brochure.pdf'),
  ('Hisense', 'Hisense KC', 'https://www.hummingbird-ac.com/wp-content/uploads/2024/07/Hisense-KC-2024.pdf'),
  ('Hisense', 'Hisense KD', 'https://media.bbairtrading.com/2026/03/KD-CATALOG_new-2026.pdf'),
  ('Hisense', 'Cassette Mark5', 'https://dasintergroup.com/daswp/wp-content/uploads/2022/01/HISENSE-Mark5-Cassette-Type-Series-Brochure.pdf'),
  ('Hisense', 'Floor', 'https://dasintergroup.com/daswp/wp-content/uploads/2024/07/Hisense-Mark5-Ceiling-Floor-Series-Brochure.pdf'),
  ('AUX', 'AUX MA', 'https://mws-data.auxair.com/upload/2025-12-29/1766991902162_b5c6f1c4-d274-4af7-80e2-3dd0181ec833.pdf'),
  ('AUX', 'AUX MF', 'https://mws-data.auxair.com/upload/2025-12-29/1766991902162_b5c6f1c4-d274-4af7-80e2-3dd0181ec833.pdf')
) as v(brand, name, url)
where s.brand = v.brand and s.name = v.name and s.brochure_url is null;

-- ✅ ตรวจผล: กี่ตัวได้รูป / กี่รุ่นได้โบรชัวร์ / เหลือตัวไหนยังไม่มีรูป
select count(*) filter (where photo_url is not null and photo_url <> '') as มีรูปแล้ว,
       count(*) filter (where photo_url is null or photo_url = '') as ยังไม่มีรูป
from materials where kind = 'ac';
select count(*) filter (where brochure_url is not null) as มีโบรชัวร์, count(*) as รุ่นทั้งหมด from ac_series;
select coalesce(brand,'?') as ยี่ห้อ, series as รุ่น, count(*) as จำนวน
from materials where kind = 'ac' and (photo_url is null or photo_url = '')
group by 1, 2 order by 1, 2;
