-- 152: เงื่อนไขรับประกันแอร์รายซีรีส์ (แทนข้อความรวมระดับยี่ห้อจาก mig 140)
-- ที่มา: เว็บ/โบรชัวร์/ภาพสเปกผู้ผลิต ผ่านการค้น + ตรวจสอบแย้ง 18 ก.ค. 2026
-- ซีรีส์ที่ยังไม่มีข้อมูลยืนยันได้ คงข้อความเดิมไว้ (ไม่เดาตัวเลขลงเอกสารลูกค้า)

update materials set warranty='คอมเพรสเซอร์ 5 ปี · อะไหล่ 2 ปี' where kind='ac' and brand='Amena' and series='AMENA WL';
update materials set warranty='คอมเพรสเซอร์ 10 ปี · อะไหล่ 2 ปี' where kind='ac' and brand='Amena' and series='AMENA WR';
update materials set warranty='คอมเพรสเซอร์ 5 ปี · อะไหล่ 2 ปี' where kind='ac' and brand='Amena' and series='Type DCC';
update materials set warranty='คอมเพรสเซอร์ 10 ปี · อะไหล่ 5 ปี (ยังไม่ยืนยัน — ห้ามพิมพ์จนกว่าจะได้เอกสารจากผู้แทนจำหน่าย)' where kind='ac' and brand='AUX' and series='AUX MF';
update materials set warranty='คอมเพรสเซอร์ 1 ปี · อะไหล่ 1 ปี' where kind='ac' and brand='Carrier' and series='40QBU';
update materials set warranty='คอมเพรสเซอร์ 5 ปี · อะไหล่ 1 ปี' where kind='ac' and brand='Carrier' and series='Apollo lll';
update materials set warranty='คอมเพรสเซอร์ 7 ปี · อะไหล่ 2 ปี' where kind='ac' and brand='Carrier' and series='Cassette TGEV';
update materials set warranty='คอมเพรสเซอร์ 5 ปี · อะไหล่ 1 ปี' where kind='ac' and brand='Carrier' and series='Cassette TGF';
update materials set warranty='คอมเพรสเซอร์ 7 ปี · อะไหล่ 2 ปี' where kind='ac' and brand='Carrier' and series='Cassette TGV';
update materials set warranty='คอมเพรสเซอร์ 5 ปี · อะไหล่ 1 ปี' where kind='ac' and brand='Carrier' and series='Cassette VLJ';
update materials set warranty='คอมเพรสเซอร์ 7 ปี · อะไหล่ 2 ปี' where kind='ac' and brand='Carrier' and series='Ceiling TGEV';
update materials set warranty='คอมเพรสเซอร์ 5 ปี · อะไหล่ 1 ปี' where kind='ac' and brand='Carrier' and series='Ceiling TGF';
update materials set warranty='คอมเพรสเซอร์ 7 ปี · อะไหล่ 2 ปี' where kind='ac' and brand='Carrier' and series='Ceiling TGV';
update materials set warranty='อะไหล่ 1 ปี' where kind='ac' and brand='Carrier' and series='FCU';
update materials set warranty='คอมเพรสเซอร์ 7 ปี · อะไหล่ 3 ปี · ฟรีค่าแรง 1 ปี' where kind='ac' and brand='Carrier' and series='NSAA';
update materials set warranty='คอมเพรสเซอร์ 10 ปี · อะไหล่ 5 ปี · ฟรีค่าแรง 1 ปี' where kind='ac' and brand='Carrier' and series='NVAA';
update materials set warranty='คอมเพรสเซอร์ 5 ปี · อะไหล่ 1 ปี' where kind='ac' and brand='Carrier' and series='TGF';
update materials set warranty='คอมเพรสเซอร์ 7 ปี · อะไหล่ 2 ปี' where kind='ac' and brand='Carrier' and series='TGV';
update materials set warranty='คอมเพรสเซอร์ 7 ปี · อะไหล่ 3 ปี · ฟรีค่าแรง 3 ปี' where kind='ac' and brand='Carrier' and series='TSAA';
update materials set warranty='คอมเพรสเซอร์ 10 ปี · อะไหล่ 5 ปี · ฟรีค่าแรง 3 ปี' where kind='ac' and brand='Carrier' and series='TVAB';
update materials set warranty='คอมเพรสเซอร์ 5 ปี · อะไหล่ 1 ปี' where kind='ac' and brand='Carrier' and series='Way TGF';
update materials set warranty='คอมเพรสเซอร์ 7 ปี · อะไหล่ 2 ปี' where kind='ac' and brand='Carrier' and series='Way TGV';
update materials set warranty='คอมเพรสเซอร์ 5 ปี · อะไหล่ 2 ปี' where kind='ac' and brand='Central' and series='Cassette IVSA';
update materials set warranty='คอมเพรสเซอร์ 5 ปี · อะไหล่ 2 ปี' where kind='ac' and brand='Central' and series='Ceiling IVSA';
update materials set warranty='คอมเพรสเซอร์ 1 ปี · อะไหล่ 1 ปี' where kind='ac' and brand='Central' and series='Central ES';
update materials set warranty='คอมเพรสเซอร์ 10 ปี · อะไหล่ 2 ปี' where kind='ac' and brand='Central' and series='Central IVGE';
update materials set warranty='คอมเพรสเซอร์ 10 ปี · อะไหล่ 5 ปี' where kind='ac' and brand='Central' and series='Central IVJS';
update materials set warranty='คอมเพรสเซอร์ 10 ปี · อะไหล่ 5 ปี' where kind='ac' and brand='Central' and series='Central IVM';
update materials set warranty='คอมเพรสเซอร์ 10 ปี · อะไหล่ 3 ปี' where kind='ac' and brand='Central' and series='Central JSFE';
update materials set warranty='คอมเพรสเซอร์ 10 ปี · อะไหล่ 3 ปี' where kind='ac' and brand='Central' and series='Central MFE';
update materials set warranty='คอมเพรสเซอร์ 1 ปี · อะไหล่ 1 ปี' where kind='ac' and brand='Central' and series='DA';
update materials set warranty='คอมเพรสเซอร์ 2 ปี · อะไหล่ 2 ปี' where kind='ac' and brand='Central' and series='Standing ME';
update materials set warranty='คอมเพรสเซอร์ 5 ปี · คอยล์เย็น 3 ปี · อะไหล่อื่น 1 ปี · ฟรีค่าแรง 1 ปี' where kind='ac' and brand='Daikin' and series='Cassette FCC';
update materials set warranty='คอมเพรสเซอร์ 5 ปี · คอยล์ร้อน 3 ปี (24/30/36k BTU) หรือ 1 ปี (13/18k BTU) · อะไหล่อื่น 1 ปี · ฟรีค่าแรง 1 ปี' where kind='ac' and brand='Daikin' and series='Ceiling FHNQ';
update materials set warranty='คอมเพรสเซอร์ 5 ปี · คอยล์เย็น 3 ปี · อะไหล่อื่น 1 ปี · ฟรีค่าแรง 1 ปี' where kind='ac' and brand='Daikin' and series='Daikin FTM';
update materials set warranty='คอมเพรสเซอร์ 5 ปี · PCB เครื่องภายนอก 3 ปี · คอยล์เย็น 3 ปี · คอยล์ร้อน 3 ปี · อะไหล่อื่น 1 ปี · ฟรีค่าแรง 1 ปี' where kind='ac' and brand='Daikin' and series='FBA';
update materials set warranty='คอมเพรสเซอร์ 5 ปี · PCB เครื่องภายนอก 3 ปี · คอยล์เย็น 3 ปี · คอยล์ร้อน 3 ปี · อะไหล่อื่น 1 ปี · ฟรีค่าแรง 1 ปี' where kind='ac' and brand='Daikin' and series='FBFC';
update materials set warranty='คอมเพรสเซอร์ 5 ปี · PCB เครื่องภายนอก 3 ปี · คอยล์เย็น 3 ปี · คอยล์ร้อน 3 ปี · อะไหล่อื่น 1 ปี · ฟรีค่าแรง 1 ปี' where kind='ac' and brand='Daikin' and series='FCTF';
update materials set warranty='คอมเพรสเซอร์ 5 ปี · PCB เครื่องภายนอก 3 ปี · คอยล์เย็น 3 ปี · คอยล์ร้อน 3 ปี · อะไหล่อื่น 1 ปี · ฟรีค่าแรง 1 ปี' where kind='ac' and brand='Daikin' and series='FDBF';
update materials set warranty='คอมเพรสเซอร์ 5 ปี · PCB เครื่องภายนอก 3 ปี · คอยล์เย็น 3 ปี · คอยล์ร้อน 3 ปี (30,000 BTU) หรือ 1 ปี (36,000 BTU) · อะไหล่อื่น 1 ปี · ฟรีค่าแรง 1 ปี' where kind='ac' and brand='Daikin' and series='STAR FAVF';
update materials set warranty='คอมเพรสเซอร์ 5 ปี · แผงวงจร PCB (ใน/นอก) 5 ปี · คอยล์เย็น 5 ปี · อะไหล่อื่น 1 ปี · ฟรีค่าแรง 1 ปี' where kind='ac' and brand='Daikin' and series='STAR KB';
update materials set warranty='คอมเพรสเซอร์ 5 ปี · แผงวงจร PCB (ใน/นอก) 5 ปี · คอยล์เย็น 5 ปี · คอยล์ร้อน 5 ปี · อะไหล่อื่น 1 ปี · ฟรีค่าแรง 1 ปี' where kind='ac' and brand='Daikin' and series='STAR KF';
update materials set warranty='คอมเพรสเซอร์ 5 ปี · แผงวงจร PCB (ใน/นอก) 5 ปี · คอยล์เย็น 5 ปี · คอยล์ร้อน 5 ปี · อะไหล่อื่น 1 ปี · ฟรีค่าแรง 1 ปี' where kind='ac' and brand='Daikin' and series='STAR KM';
update materials set warranty='คอมเพรสเซอร์ 5 ปี · แผงวงจร PCB (ใน/นอก) 5 ปี · คอยล์เย็น 5 ปี · อะไหล่อื่น 1 ปี · ฟรีค่าแรง 1 ปี' where kind='ac' and brand='Daikin' and series='STAR KQ';
update materials set warranty='คอมเพรสเซอร์ 5 ปี · แผงวงจร PCB (ใน/นอก) 5 ปี · คอยล์เย็น 5 ปี · คอยล์ร้อน 5 ปี · อะไหล่อื่น 1 ปี · ฟรีค่าแรง 1 ปี' where kind='ac' and brand='Daikin' and series='STAR KZ';
update materials set warranty='คอมเพรสเซอร์ 5 ปี · อะไหล่ 2 ปี' where kind='ac' and brand='Eminent' and series='SUPER KOOM';
update materials set warranty='คอมเพรสเซอร์ 10 ปี · อะไหล่ 5 ปี · ฟรีค่าบริการตรวจเช็ค 1 ปี' where kind='ac' and brand='Gree' and series='Cap';
update materials set warranty='คอมเพรสเซอร์ 10 ปี · อะไหล่ 5 ปี · ฟรีค่าบริการตรวจเช็ค 1 ปี' where kind='ac' and brand='Gree' and series='Gree SAVI';
update materials set warranty='คอมเพรสเซอร์ 10 ปี · อะไหล่ 5 ปี · ฟรีค่าบริการตรวจเช็ค 1 ปี' where kind='ac' and brand='Gree' and series='PULAR I1';
update materials set warranty='ตัวเครื่อง/อะไหล่ 5 ปี · คอมเพรสเซอร์ 5 ปี' where kind='ac' and brand='Haier' and series='Ceiling HCFU';
update materials set warranty='ตัวเครื่อง/อะไหล่ 5 ปี · คอมเพรสเซอร์ 10 ปี' where kind='ac' and brand='Haier' and series='Cool Plus';
update materials set warranty='ตัวเครื่อง/อะไหล่ 5 ปี · คอมเพรสเซอร์ 10 ปี' where kind='ac' and brand='Haier' and series='Flow HCSI';
update materials set warranty='ตัวเครื่อง/อะไหล่ 5 ปี · คอมเพรสเซอร์ 5 ปี' where kind='ac' and brand='Haier' and series='Flow HCSU';
update materials set warranty='ตัวเครื่อง/อะไหล่ 5 ปี · คอมเพรสเซอร์ 10 ปี' where kind='ac' and brand='Haier' and series='HDI';
update materials set warranty='ตัวเครื่อง/อะไหล่ 5 ปี · คอมเพรสเซอร์ 10 ปี' where kind='ac' and brand='Haier' and series='Way HCS1';
update materials set warranty='คอมเพรสเซอร์ 12 ปี · อะไหล่ 3 ปี' where kind='ac' and brand='Hisense' and series='Cassette Mark5';
update materials set warranty='คอมเพรสเซอร์ 12 ปี · อะไหล่ 3 ปี' where kind='ac' and brand='Hisense' and series='Floor';
update materials set warranty='คอมเพรสเซอร์ 12 ปี · อะไหล่ 5 ปี' where kind='ac' and brand='Hisense' and series='Hisense KC';
update materials set warranty='คอมเพรสเซอร์ 12 ปี · อะไหล่ 5 ปี' where kind='ac' and brand='Hisense' and series='Hisense KD';
update materials set warranty='คอมเพรสเซอร์ 5 ปี · คอยล์ร้อน CAZ 3 ปี · แผง PCB 3 ปี · อะไหล่อื่น 1 ปี · ฟรีค่าแรง 1 ปี' where kind='ac' and brand='Daikin' and series='Ceiling FHA';
update materials set warranty='คอมเพรสเซอร์ 5 ปี · คอยล์ร้อน CAZ 3 ปี · แผง PCB 3 ปี · อะไหล่อื่น 1 ปี · ฟรีค่าแรง 1 ปี' where kind='ac' and brand='Daikin' and series='FCF';
update materials set warranty='คอมเพรสเซอร์ 5 ปี · คอยล์เย็น 3 ปี · คอยล์ร้อน 3 ปี · แผง PCB 3 ปี · อะไหล่อื่น 1 ปี · ฟรีค่าแรง 1 ปี' where kind='ac' and brand='Daikin' and series='Ceiling FHFC';
update materials set warranty='คอมเพรสเซอร์ 5 ปี · คอยล์เย็น 3 ปี · คอยล์ร้อน 3 ปี · แผง PCB 3 ปี · อะไหล่อื่น 1 ปี · ฟรีค่าแรง 1 ปี' where kind='ac' and brand='Daikin' and series='FCFC';
update materials set warranty='คอมเพรสเซอร์ 5 ปี · คอยล์เย็น 3 ปี · คอยล์ร้อน 3 ปี · อะไหล่อื่น 1 ปี · ฟรีค่าแรง 1 ปี' where kind='ac' and brand='Mitsubishi Electric' and series='SE';
update materials set warranty='คอมเพรสเซอร์ 10 ปี · อะไหล่ 5 ปี' where kind='ac' and brand='AUX' and series='AUX MA';
update materials set warranty='คอมเพรสเซอร์ 5 ปี · อะไหล่ 5 ปี · ฟรีค่าแรง 5 ปี' where kind='ac' and brand='Haier' and series='HSU' and code like '%CQRC%';
update materials set warranty='คอมเพรสเซอร์ 10 ปี · อะไหล่ 5 ปี · ฟรีค่าแรง 5 ปี' where kind='ac' and brand='Haier' and series='HSU' and code not like '%CQRC%';
update materials set warranty='คอมเพรสเซอร์ 10 ปี · อะไหล่ 5 ปี · ฟรีค่าแรง 1 ปี' where kind='ac' and brand='Carrier' and series='TVDB';
update materials set warranty='คอมเพรสเซอร์ 10 ปี · อะไหล่ 5 ปี · ฟรีค่าแรงซ่อม 3 ปี' where kind='ac' and brand='Carrier' and series='TVEB';
update materials set warranty='คอมเพรสเซอร์ 12 ปี · อะไหล่ 5 ปี' where code='AS-24TRLB2T';
update materials set warranty='คอมเพรสเซอร์ 5 ปี · ตัวเครื่อง/อะไหล่ 1 ปี (ไม่รวมค่าแรง ค่าเดินทาง และอะไหล่เพื่อความสวยงาม)' where kind='ac' and brand='LG' and series='Cassette ZTNQ';
update materials set warranty='คอมเพรสเซอร์ 5 ปี · ตัวเครื่อง/อะไหล่ 1 ปี (ไม่รวมค่าแรง ค่าเดินทาง และอะไหล่เพื่อความสวยงาม)' where kind='ac' and brand='LG' and series='Ceiling ZVNQ';
update materials set warranty='คอมเพรสเซอร์ 10 ปี · ตัวเครื่อง 1 ปี · อะไหล่ 3 ปี (ไม่รวมค่าแรงและค่าทำระบบน้ำยา) — สำหรับลูกค้าที่ซื้อตั้งแต่ 1 มกราคม 2568' where kind='ac' and brand='LG' and series='VICTORY IKR';
update materials set warranty='คอมเพรสเซอร์ 10 ปี · อะไหล่ 5 ปี · ฟรีค่าแรง 5 ปี' where kind='ac' and brand='Midea' and series='Cassette LCAC';
update materials set warranty='คอมเพรสเซอร์ 10 ปี · อะไหล่ 5 ปี · ฟรีค่าแรง 5 ปี' where kind='ac' and brand='Midea' and series='Ceiling LCAC';
update materials set warranty='คอมเพรสเซอร์ 7 ปี · อะไหล่ 5 ปี · ฟรีค่าแรง 5 ปี' where kind='ac' and brand='Midea' and series='Ceiling ME';
update materials set warranty='คอมเพรสเซอร์ 10 ปี · อะไหล่ 5 ปี · ฟรีค่าแรง 5 ปี' where kind='ac' and brand='Midea' and series='MFA';
update materials set warranty='คอมเพรสเซอร์ 7 ปี · อะไหล่ 5 ปี · ฟรีค่าแรง 5 ปี' where kind='ac' and brand='Midea' and series='MFGA';
update materials set warranty='คอมเพรสเซอร์ 7 ปี · อะไหล่ 5 ปี · ฟรีค่าแรง 5 ปี' where kind='ac' and brand='Midea' and series='MFJ';
update materials set warranty='คอมเพรสเซอร์ 7 ปี · อะไหล่ 5 ปี · ฟรีค่าแรง 5 ปี' where kind='ac' and brand='Midea' and series='MFTM';
update materials set warranty='คอมเพรสเซอร์ 10 ปี · อะไหล่ 5 ปี · ฟรีค่าแรง 5 ปี' where kind='ac' and brand='Midea' and series='Midea Celest';
update materials set warranty='คอมเพรสเซอร์ 10 ปี · อะไหล่ 5 ปี · ฟรีค่าแรง 5 ปี' where kind='ac' and brand='Midea' and series='Midea Numen';
update materials set warranty='คอมเพรสเซอร์ 10 ปี · อะไหล่ 5 ปี · ฟรีค่าแรง 5 ปี' where kind='ac' and brand='Midea' and series='MSEPB';
update materials set warranty='คอมเพรสเซอร์ 10 ปี · อะไหล่ 5 ปี · ฟรีค่าแรง 5 ปี' where kind='ac' and brand='Midea' and series='MSEPC';
update materials set warranty='คอมเพรสเซอร์ 10 ปี · อะไหล่ 5 ปี · ฟรีค่าแรง 5 ปี' where kind='ac' and brand='Midea' and series='MTI';
update materials set warranty='คอมเพรสเซอร์ 10 ปี · อะไหล่ 5 ปี · ฟรีค่าแรง 5 ปี' where kind='ac' and brand='Midea' and series='MTIU';
update materials set warranty='คอมเพรสเซอร์ 7 ปี · อะไหล่ 5 ปี · ฟรีค่าแรง 5 ปี' where kind='ac' and brand='Midea' and series='Torndo Easy';
update materials set warranty='คอมเพรสเซอร์ 5 ปี · แผงคอยล์ร้อน-เย็น 3 ปี · อะไหล่ภายในตัวเครื่อง 1 ปี' where kind='ac' and brand='Mitsubishi Electric' and series='AW';
update materials set warranty='คอมเพรสเซอร์ 5 ปี · แผงคอยล์ร้อน-เย็น 3 ปี · อะไหล่ภายในตัวเครื่อง 1 ปี' where kind='ac' and brand='Mitsubishi Electric' and series='Cassette PL';
update materials set warranty='คอมเพรสเซอร์ 5 ปี · แผงคอยล์ร้อน-เย็น 3 ปี · อะไหล่ภายในตัวเครื่อง 1 ปี' where kind='ac' and brand='Mitsubishi Electric' and series='GY';
update materials set warranty='คอมเพรสเซอร์ 5 ปี · แผงคอยล์ร้อน-เย็น 3 ปี · อะไหล่ภายในตัวเครื่อง 1 ปี' where kind='ac' and brand='Mitsubishi Electric' and series='GZ';
update materials set warranty='คอมเพรสเซอร์ 5 ปี · แผงคอยล์ร้อน-เย็น 3 ปี · อะไหล่ภายในตัวเครื่อง 1 ปี' where kind='ac' and brand='Mitsubishi Electric' and series='JY';
update materials set warranty='คอมเพรสเซอร์ 5 ปี · แผงคอยล์ร้อน-เย็น 3 ปี · อะไหล่ภายในตัวเครื่อง 1 ปี' where kind='ac' and brand='Mitsubishi Electric' and series='JZ';
update materials set warranty='คอมเพรสเซอร์ 5 ปี · แผงคอยล์ร้อน-เย็น 3 ปี · อะไหล่ภายในตัวเครื่อง 1 ปี' where kind='ac' and brand='Mitsubishi Electric' and series='KA';
update materials set warranty='คอมเพรสเซอร์ 5 ปี · แผงคอยล์ร้อน-เย็น 3 ปี · อะไหล่ภายในตัวเครื่อง 1 ปี' where kind='ac' and brand='Mitsubishi Electric' and series='M';
update materials set warranty='คอมเพรสเซอร์ 5 ปี · แผงคอยล์ร้อน-เย็น 3 ปี · อะไหล่ภายในตัวเครื่อง 1 ปี' where kind='ac' and brand='Mitsubishi Electric' and series='PEY';
update materials set warranty='คอมเพรสเซอร์ 5 ปี · แผงคอยล์ร้อน-เย็น 3 ปี · อะไหล่ภายในตัวเครื่อง 1 ปี' where kind='ac' and brand='Mitsubishi Electric' and series='PLY';
update materials set warranty='คอมเพรสเซอร์ 5 ปี · แผงคอยล์ร้อน-เย็น 3 ปี · อะไหล่ภายในตัวเครื่อง 1 ปี' where kind='ac' and brand='Mitsubishi Electric' and series='SM';
update materials set warranty='คอมเพรสเซอร์ 5 ปี · แผงคอยล์ร้อน-เย็น 3 ปี · อะไหล่ภายในตัวเครื่อง 1 ปี' where kind='ac' and brand='Mitsubishi Electric' and series='XZ';
update materials set warranty='คอมเพรสเซอร์ 5 ปี · อะไหล่ 5 ปี · ไม่รวมค่าบริการ/ค่าแรง' where kind='ac' and brand='Mitsubishi Heavy Duty' and series='Cassette FDT';
update materials set warranty='คอมเพรสเซอร์ 5 ปี · อะไหล่ 5 ปี · ไม่รวมค่าบริการ/ค่าแรง' where kind='ac' and brand='Mitsubishi Heavy Duty' and series='Ceiling FDE';
update materials set warranty='คอมเพรสเซอร์ 5 ปี · อะไหล่ 5 ปี · ไม่รวมค่าบริการ/ค่าแรง' where kind='ac' and brand='Mitsubishi Heavy Duty' and series='Duty Fuyu';
update materials set warranty='คอมเพรสเซอร์ 5 ปี · อะไหล่ 5 ปี · ไม่รวมค่าบริการ/ค่าแรง' where kind='ac' and brand='Mitsubishi Heavy Duty' and series='Duty Haru';
update materials set warranty='คอมเพรสเซอร์ 5 ปี · อะไหล่ 5 ปี · ไม่รวมค่าบริการ/ค่าแรง' where kind='ac' and brand='Mitsubishi Heavy Duty' and series='Duty Hoshi';
update materials set warranty='คอมเพรสเซอร์ 5 ปี · อะไหล่ 5 ปี · ไม่รวมค่าบริการ/ค่าแรง' where kind='ac' and brand='Mitsubishi Heavy Duty' and series='Duty Kaze';
update materials set warranty='คอมเพรสเซอร์ 5 ปี · อะไหล่ 5 ปี · ไม่รวมค่าบริการ/ค่าแรง' where kind='ac' and brand='Mitsubishi Heavy Duty' and series='Duty Yuki';
update materials set warranty='คอมเพรสเซอร์ 5 ปี · อะไหล่ 5 ปี · ไม่รวมค่าบริการ/ค่าแรง' where kind='ac' and brand='Mitsubishi Heavy Duty' and series='FDUM';
update materials set warranty='คอมเพรสเซอร์ 5 ปี · อะไหล่ 5 ปี · ไม่รวมค่าบริการ/ค่าแรง' where kind='ac' and brand='Mitsubishi Heavy Duty' and series='SRK';
update materials set warranty='คอมเพรสเซอร์ 10 ปี · แผงคอยล์ร้อน/เย็น 3 ปี · อะไหล่ 1 ปี · ฟรีค่าแรง 1 ปี (ยืนยันแน่นอนเฉพาะส่วน ''อะไหล่ 1 ปี + ฟรีค่าแรง/ค่าเดินทาง'' — ตัวเลขคอมเพรสเซอร์/คอยล์ยังไม่มีแหล่งทางการรายซีรีส์ ควรยืนยันกับ Samsung ก่อนพิมพ์ผูกมัดลูกค้า)' where kind='ac' and brand='Samsung' and series='360 CST';
update materials set warranty='คอมเพรสเซอร์ 10 ปี · แผงคอยล์ร้อน/เย็น 3 ปี · อะไหล่ 1 ปี · ฟรีค่าแรง 1 ปี (ยืนยันแน่นอนเฉพาะส่วน ''อะไหล่ 1 ปี + ฟรีค่าแรง/ค่าเดินทาง'' — ตัวเลขคอมเพรสเซอร์/คอยล์ยังไม่มีแหล่งทางการรายซีรีส์ ควรยืนยันกับ Samsung ก่อนพิมพ์ผูกมัดลูกค้า)' where kind='ac' and brand='Samsung' and series='AC';
update materials set warranty='คอมเพรสเซอร์ 10 ปี · แผงคอยล์ร้อน/เย็น 3 ปี · อะไหล่ 1 ปี · ฟรีค่าแรง 1 ปี (ลงทะเบียนภายใน 90 วันนับจากวันซื้อ ขยายคอยล์/อะไหล่/ค่าแรงเป็น 5 ปี — เฉพาะสินค้าที่ซื้อในช่วง 1 ม.ค.–31 ธ.ค. 2569 และเฉพาะรุ่นในลิสต์ 5 ปี เช่น AR80F/AR70/AR60 ส่วน AR50H/DYHZB/CYEC/CYHC ได้ 3 ปี)' where kind='ac' and brand='Samsung' and series='AR';
update materials set warranty='คอมเพรสเซอร์ 10 ปี · แผงคอยล์ร้อน/เย็น 3 ปี · อะไหล่ 1 ปี · ฟรีค่าแรง 1 ปี (ยืนยันแน่นอนเฉพาะส่วน ''อะไหล่ 1 ปี + ฟรีค่าแรง/ค่าเดินทาง'' — ตัวเลขคอมเพรสเซอร์/คอยล์ยังไม่มีแหล่งทางการรายซีรีส์ ควรยืนยันกับ Samsung ก่อนพิมพ์ผูกมัดลูกค้า)' where kind='ac' and brand='Samsung' and series='Cassette WindFree';
update materials set warranty='คอมเพรสเซอร์ 10 ปี · อะไหล่ 2 ปี' where kind='ac' and brand='Star aire' and series='Star DM';
update materials set warranty='คอมเพรสเซอร์ 5 ปี · อะไหล่ 2 ปี (ใช้ได้เฉพาะรุ่น FIV แท้ 3 ขนาด: DM-095/125 FIV และ DM-185 FIVA เท่านั้น)' where kind='ac' and brand='Star aire' and series='Star FIV';
update materials set warranty='คอมเพรสเซอร์ 10 ปี · อะไหล่ 5 ปี (เฉพาะซื้อผ่านช่องทางออฟไลน์จากตัวแทนจำหน่ายที่ได้รับแต่งตั้ง — ซื้อออนไลน์ คอมเพรสเซอร์ 5 ปี · อะไหล่ 1 ปี)' where kind='ac' and brand='TCL' and series='BreezeIN Premium';
update materials set warranty='คอมเพรสเซอร์ 10 ปี · อะไหล่ 5 ปี (เฉพาะซื้อผ่านช่องทางออฟไลน์จากตัวแทนจำหน่ายที่ได้รับแต่งตั้ง — ซื้อออนไลน์ คอมเพรสเซอร์ 5 ปี · อะไหล่ 1 ปี)' where kind='ac' and brand='TCL' and series='BreezeIN WiFi';
update materials set warranty='คอมเพรสเซอร์ 10 ปี · อะไหล่ 5 ปี (เฉพาะซื้อผ่านช่องทางออฟไลน์จากตัวแทนจำหน่ายที่ได้รับแต่งตั้ง — ซื้อออนไลน์ คอมเพรสเซอร์ 5 ปี · อะไหล่ 1 ปี)' where kind='ac' and brand='TCL' and series='CA';
update materials set warranty='คอมเพรสเซอร์ 10 ปี · อะไหล่ 5 ปี (เฉพาะซื้อผ่านช่องทางออฟไลน์จากตัวแทนจำหน่ายที่ได้รับแต่งตั้ง — ซื้อออนไลน์ คอมเพรสเซอร์ 5 ปี · อะไหล่ 1 ปี)' where kind='ac' and brand='TCL' and series='CE';
update materials set warranty='คอมเพรสเซอร์ 10 ปี · อะไหล่ 5 ปี (เฉพาะซื้อผ่านช่องทางออฟไลน์จากตัวแทนจำหน่ายที่ได้รับแต่งตั้ง — ซื้อออนไลน์ คอมเพรสเซอร์ 5 ปี · อะไหล่ 1 ปี)' where kind='ac' and brand='TCL' and series='SaveIN F1';
update materials set warranty='คอมเพรสเซอร์ 10 ปี · อะไหล่ 5 ปี (เฉพาะซื้อผ่านช่องทางออฟไลน์จากตัวแทนจำหน่ายที่ได้รับแต่งตั้ง — ซื้อออนไลน์ คอมเพรสเซอร์ 5 ปี · อะไหล่ 1 ปี)' where kind='ac' and brand='TCL' and series='TAC';
update materials set warranty='คอมเพรสเซอร์ 10 ปี · อะไหล่ 5 ปี (เฉพาะซื้อผ่านช่องทางออฟไลน์จากตัวแทนจำหน่ายที่ได้รับแต่งตั้ง — ซื้อออนไลน์ คอมเพรสเซอร์ 5 ปี · อะไหล่ 1 ปี)' where kind='ac' and brand='TCL' and series='TCL SaveIN';
update materials set warranty='คอมเพรสเซอร์ 10 ปี · อะไหล่ 5 ปี (เฉพาะซื้อผ่านช่องทางออฟไลน์จากตัวแทนจำหน่ายที่ได้รับแต่งตั้ง — ซื้อออนไลน์ คอมเพรสเซอร์ 5 ปี · อะไหล่ 1 ปี)' where kind='ac' and brand='TCL' and series='TCL VOXIN';

-- ✅ ตรวจผล: รุ่นที่ยังใช้ข้อความรวมระดับยี่ห้ออยู่ (ควรเหลือน้อยที่สุด)
select brand, series, count(*) n from materials where kind='ac' and active and warranty like '%ตามซีรีส์%' group by 1,2 order by n desc;
